//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-cocoa/src/main/java//im/actor/runtime/CryptoRuntimeProvider.java
//

#include <j2objc/J2ObjC_source.h>
#include "im/actor/runtime/CryptoRuntimeProvider.h"
#include "im/actor/runtime/cocoa/CocoaCryptoProvider.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-cocoa/src/main/java//im/actor/runtime/CryptoRuntimeProvider.java"


#line 5
@implementation ARCryptoRuntimeProvider

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ARCryptoRuntimeProvider_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _ARCryptoRuntimeProvider = { 2, "CryptoRuntimeProvider", "im.actor.runtime", NULL, 0x1, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ARCryptoRuntimeProvider;
}

@end

void ARCryptoRuntimeProvider_init(ARCryptoRuntimeProvider *self) {
  (void) ARCocoaCryptoProvider_init(self);
}

ARCryptoRuntimeProvider *new_ARCryptoRuntimeProvider_init() {
  ARCryptoRuntimeProvider *self = [ARCryptoRuntimeProvider alloc];
  ARCryptoRuntimeProvider_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ARCryptoRuntimeProvider)

#pragma clang diagnostic pop
