//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/internal/messages/entity/PendingMessagesStorage.java
//

#ifndef _ImActorCoreModulesInternalMessagesEntityPendingMessagesStorage_H_
#define _ImActorCoreModulesInternalMessagesEntityPendingMessagesStorage_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/runtime/bser/BserObject.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@class JavaUtilArrayList;

@interface ACPendingMessagesStorage : ARBserObject

#pragma mark Public

- (instancetype)init;

+ (ACPendingMessagesStorage *)fromBytesWithByteArray:(IOSByteArray *)data;

- (JavaUtilArrayList *)getPendingMessages;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPendingMessagesStorage)

FOUNDATION_EXPORT ACPendingMessagesStorage *ACPendingMessagesStorage_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ACPendingMessagesStorage_init(ACPendingMessagesStorage *self);

FOUNDATION_EXPORT ACPendingMessagesStorage *new_ACPendingMessagesStorage_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACPendingMessagesStorage)

@compatibility_alias ImActorCoreModulesInternalMessagesEntityPendingMessagesStorage ACPendingMessagesStorage;


#pragma clang diagnostic pop
#endif // _ImActorCoreModulesInternalMessagesEntityPendingMessagesStorage_H_
