//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/internal/messages/entity/PlainCursor.java
//

#ifndef _ImActorCoreModulesInternalMessagesEntityPlainCursor_H_
#define _ImActorCoreModulesInternalMessagesEntityPlainCursor_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/runtime/bser/BserObject.h"

@class ACPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

@interface ACPlainCursor : ARBserObject

#pragma mark Public

- (instancetype)initWithACPeer:(ACPeer *)peer
                      withLong:(jlong)sortDate
                      withLong:(jlong)pendingSortDate;

- (ACPlainCursor *)changePendingSortDateWithLong:(jlong)pendingDate;

- (ACPlainCursor *)changeSortDateWithLong:(jlong)date;

+ (ACPlainCursor *)fromBytesWithByteArray:(IOSByteArray *)data;

- (ACPeer *)getPeer;

- (jlong)getPendingSortDate;

- (jlong)getSortDate;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPlainCursor)

FOUNDATION_EXPORT ACPlainCursor *ACPlainCursor_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ACPlainCursor_initWithACPeer_withLong_withLong_(ACPlainCursor *self, ACPeer *peer, jlong sortDate, jlong pendingSortDate);

FOUNDATION_EXPORT ACPlainCursor *new_ACPlainCursor_initWithACPeer_withLong_withLong_(ACPeer *peer, jlong sortDate, jlong pendingSortDate) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACPlainCursor)

@compatibility_alias ImActorCoreModulesInternalMessagesEntityPlainCursor ACPlainCursor;


#pragma clang diagnostic pop
#endif // _ImActorCoreModulesInternalMessagesEntityPlainCursor_H_
