//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/viewmodel/AvatarUploadState.java
//

#ifndef _ImActorCoreViewmodelAvatarUploadState_H_
#define _ImActorCoreViewmodelAvatarUploadState_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>

/*!
 @brief Avatar upload state
 */
@interface ACAvatarUploadState : NSObject
@property (readonly, copy, nonatomic, getter=getDescriptor) NSString *descriptor;
@property (readonly, nonatomic, getter=isUploading) jboolean isUploading;

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)descriptor
                     withBoolean:(jboolean)isUploading;

/*!
 @brief Uploading descriptor
 @return file system descriptor
 */
- (NSString *)getDescriptor;

/*!
 @brief Is upload in progress
 @return is uploading
 */
- (jboolean)isUploading;

@end

J2OBJC_EMPTY_STATIC_INIT(ACAvatarUploadState)

FOUNDATION_EXPORT void ACAvatarUploadState_initWithNSString_withBoolean_(ACAvatarUploadState *self, NSString *descriptor, jboolean isUploading);

FOUNDATION_EXPORT ACAvatarUploadState *new_ACAvatarUploadState_initWithNSString_withBoolean_(NSString *descriptor, jboolean isUploading) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACAvatarUploadState)

@compatibility_alias ImActorCoreViewmodelAvatarUploadState ACAvatarUploadState;


#pragma clang diagnostic pop
#endif // _ImActorCoreViewmodelAvatarUploadState_H_
