//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/viewmodel/UploadFileCallback.java
//

#ifndef _ImActorCoreViewmodelUploadFileCallback_H_
#define _ImActorCoreViewmodelUploadFileCallback_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>

/*!
 @brief Upload file callback.
 Methods always called on background thread.
 */
@protocol ACUploadFileCallback < NSObject, JavaObject >

/*!
 @brief On File not uploading
 */
- (void)onNotUploading;

/*!
 @brief On File upload in progress
 @param progress progress value in [0..1]
 */
- (void)onUploading:(jfloat)progress;

/*!
 @brief On file uploaded
 */
- (void)onUploaded;

@end

J2OBJC_EMPTY_STATIC_INIT(ACUploadFileCallback)

J2OBJC_TYPE_LITERAL_HEADER(ACUploadFileCallback)

#define ImActorCoreViewmodelUploadFileCallback ACUploadFileCallback


#pragma clang diagnostic pop
#endif // _ImActorCoreViewmodelUploadFileCallback_H_
