//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/viewmodel/UserPhone.java
//

#ifndef _ImActorCoreViewmodelUserPhone_H_
#define _ImActorCoreViewmodelUserPhone_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>

/*!
 @brief User's Phone record
 */
@interface ACUserPhone : NSObject
@property (readonly, nonatomic, getter=getPhone) jlong phone;
@property (readonly, copy, nonatomic, getter=getTitle) NSString *title;

#pragma mark Public

/*!
 @brief <p>INTERNAL API</p>
 Create User phone
 @param phone phone in international format
 @param title title of phone
 */
- (instancetype)initWithLong:(jlong)phone
                withNSString:(NSString *)title;

- (jboolean)isEqual:(id)o;

/*!
 @brief Get Phone number
 @return phone number in international format
 */
- (jlong)getPhone;

/*!
 @brief Get Phone title
 @return phone title
 */
- (NSString *)getTitle;

- (NSUInteger)hash;

@end

J2OBJC_EMPTY_STATIC_INIT(ACUserPhone)

FOUNDATION_EXPORT void ACUserPhone_initWithLong_withNSString_(ACUserPhone *self, jlong phone, NSString *title);

FOUNDATION_EXPORT ACUserPhone *new_ACUserPhone_initWithLong_withNSString_(jlong phone, NSString *title) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACUserPhone)

@compatibility_alias ImActorCoreViewmodelUserPhone ACUserPhone;


#pragma clang diagnostic pop
#endif // _ImActorCoreViewmodelUserPhone_H_
