//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//im/actor/runtime/mtproto/ConnectionCallback.java
//

#include <j2objc/IOSClass.h>
#include <j2objc/IOSPrimitiveArray.h>
#include <j2objc/J2ObjC_source.h>
#include "com/google/j2objc/annotations/ObjectiveCName.h"
#include "im/actor/runtime/mtproto/ConnectionCallback.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ARConnectionCallback : NSObject

@end

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//im/actor/runtime/mtproto/ConnectionCallback.java"


#line 9
@implementation ARConnectionCallback

+ (IOSObjectArray *)__annotations_onConnectionRedirectWithNSString_withInt_withInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onConnectionRedirectWithHost:withPort:withTimeout:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onMessageWithByteArray_withInt_withInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onMessageWithData:withOffset:withLength:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onConnectionDie {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onConnectionDie"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "onConnectionRedirectWithHost:withPort:withTimeout:", "onConnectionRedirect", "V", 0x401, NULL, NULL },
    { "onMessageWithData:withOffset:withLength:", "onMessage", "V", 0x401, NULL, NULL },
    { "onConnectionDie", NULL, "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ARConnectionCallback = { 2, "ConnectionCallback", "im.actor.runtime.mtproto", NULL, 0x609, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ARConnectionCallback;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ARConnectionCallback)

#pragma clang diagnostic pop
