//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/updates/UpdateGroupAvatarChanged.java
//

#ifndef _ImActorCoreApiUpdatesUpdateGroupAvatarChanged_H_
#define _ImActorCoreApiUpdatesUpdateGroupAvatarChanged_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/core/network/parser/Update.h>

@class ARApiAvatar;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#define ARUpdateGroupAvatarChanged_HEADER 39

@interface ARUpdateGroupAvatarChanged : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)groupId
                   withLong:(jlong)rid
                    withInt:(jint)uid
            withARApiAvatar:(ARApiAvatar *)avatar
                   withLong:(jlong)date;

+ (ARUpdateGroupAvatarChanged *)fromBytesWithByteArray:(IOSByteArray *)data;

- (ARApiAvatar *)getAvatar;

- (jlong)getDate;

- (jint)getGroupId;

- (jint)getHeaderKey;

- (jlong)getRid;

- (jint)getUid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateGroupAvatarChanged)

J2OBJC_STATIC_FIELD_GETTER(ARUpdateGroupAvatarChanged, HEADER, jint)

FOUNDATION_EXPORT ARUpdateGroupAvatarChanged *ARUpdateGroupAvatarChanged_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateGroupAvatarChanged_initWithInt_withLong_withInt_withARApiAvatar_withLong_(ARUpdateGroupAvatarChanged *self, jint groupId, jlong rid, jint uid, ARApiAvatar *avatar, jlong date);

FOUNDATION_EXPORT ARUpdateGroupAvatarChanged *new_ARUpdateGroupAvatarChanged_initWithInt_withLong_withInt_withARApiAvatar_withLong_(jint groupId, jlong rid, jint uid, ARApiAvatar *avatar, jlong date) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARUpdateGroupAvatarChanged_init(ARUpdateGroupAvatarChanged *self);

FOUNDATION_EXPORT ARUpdateGroupAvatarChanged *new_ARUpdateGroupAvatarChanged_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateGroupAvatarChanged)

@compatibility_alias ImActorCoreApiUpdatesUpdateGroupAvatarChanged ARUpdateGroupAvatarChanged;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiUpdatesUpdateGroupAvatarChanged_H_
