//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/updates/UpdateUserLastSeen.java
//

#include <j2objc/IOSClass.h>
#include <j2objc/IOSPrimitiveArray.h>
#include <j2objc/J2ObjC_source.h>
#include "im/actor/core/api/updates/UpdateUserLastSeen.h"
#include "im/actor/core/network/parser/Update.h"
#include "im/actor/runtime/bser/Bser.h"
#include "im/actor/runtime/bser/BserObject.h"
#include "im/actor/runtime/bser/BserValues.h"
#include "im/actor/runtime/bser/BserWriter.h"
#include <j2objc/java/io/IOException.h>

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ARUpdateUserLastSeen () {
 @public
  jint uid_;
  jlong date_;
}

@end

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/updates/UpdateUserLastSeen.java"


#line 18
@implementation ARUpdateUserLastSeen

+ (jint)HEADER {
  return ARUpdateUserLastSeen_HEADER;
}


#line 21
+ (ARUpdateUserLastSeen *)fromBytesWithByteArray:(IOSByteArray *)data {
  return ARUpdateUserLastSeen_fromBytesWithByteArray_(data);
}


#line 28
- (instancetype)initWithInt:(jint)uid
                   withLong:(jlong)date {
  ARUpdateUserLastSeen_initWithInt_withLong_(self, uid, date);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 33
- (instancetype)init {
  ARUpdateUserLastSeen_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 37
- (jint)getUid {
  return self->uid_;
}

- (jlong)getDate {
  return self->date_;
}


#line 46
- (void)parseWithARBserValues:(ARBserValues *)values {
  self->uid_ = [((ARBserValues *) nil_chk(values)) getIntWithInt:1];
  self->date_ = [values getLongWithInt:2];
}


#line 52
- (void)serializeWithARBserWriter:(ARBserWriter *)writer {
  [((ARBserWriter *) nil_chk(writer)) writeIntWithInt:1 withInt:self->uid_];
  [writer writeLongWithInt:2 withLong:self->date_];
}


#line 58
- (NSString *)description {
  NSString *res = @"update UserLastSeen{";
  (void) JreStrAppendStrong(&res, "$I", @"uid=", self->uid_);
  (void) JreStrAppendStrong(&res, "$J", @", date=", self->date_);
  (void) JreStrAppendStrong(&res, "$", @"}");
  return res;
}


#line 67
- (jint)getHeaderKey {
  return ARUpdateUserLastSeen_HEADER;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "fromBytesWithByteArray:", "fromBytes", "Lim.actor.core.api.updates.UpdateUserLastSeen;", 0x9, "Ljava.io.IOException;", NULL },
    { "initWithInt:withLong:", "UpdateUserLastSeen", NULL, 0x1, NULL, NULL },
    { "init", "UpdateUserLastSeen", NULL, 0x1, NULL, NULL },
    { "getUid", NULL, "I", 0x1, NULL, NULL },
    { "getDate", NULL, "J", 0x1, NULL, NULL },
    { "parseWithARBserValues:", "parse", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "serializeWithARBserWriter:", "serialize", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getHeaderKey", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "HEADER", "HEADER", 0x19, "I", NULL, NULL, .constantValue.asInt = ARUpdateUserLastSeen_HEADER },
    { "uid_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "date_", NULL, 0x2, "J", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ARUpdateUserLastSeen = { 2, "UpdateUserLastSeen", "im.actor.core.api.updates", NULL, 0x1, 9, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ARUpdateUserLastSeen;
}

@end


#line 21
ARUpdateUserLastSeen *ARUpdateUserLastSeen_fromBytesWithByteArray_(IOSByteArray *data) {
  ARUpdateUserLastSeen_initialize();
  
#line 22
  return ARBser_parseWithARBserObject_withByteArray_(new_ARUpdateUserLastSeen_init(), data);
}

void ARUpdateUserLastSeen_initWithInt_withLong_(ARUpdateUserLastSeen *self, jint uid, jlong date) {
  (void) ACUpdate_init(self);
  
#line 29
  self->uid_ = uid;
  self->date_ = date;
}


#line 28
ARUpdateUserLastSeen *new_ARUpdateUserLastSeen_initWithInt_withLong_(jint uid, jlong date) {
  ARUpdateUserLastSeen *self = [ARUpdateUserLastSeen alloc];
  ARUpdateUserLastSeen_initWithInt_withLong_(self, uid, date);
  return self;
}


#line 33
void ARUpdateUserLastSeen_init(ARUpdateUserLastSeen *self) {
  (void) ACUpdate_init(self);
}


#line 33
ARUpdateUserLastSeen *new_ARUpdateUserLastSeen_init() {
  ARUpdateUserLastSeen *self = [ARUpdateUserLastSeen alloc];
  ARUpdateUserLastSeen_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ARUpdateUserLastSeen)

#pragma clang diagnostic pop
