//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/updates/UpdateMessageReceived.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "im/actor/core/api/ApiPeer.h"
#include "im/actor/core/api/updates/UpdateMessageReceived.h"
#include "im/actor/core/network/parser/Update.h"
#include "im/actor/runtime/bser/Bser.h"
#include "im/actor/runtime/bser/BserObject.h"
#include "im/actor/runtime/bser/BserValues.h"
#include "im/actor/runtime/bser/BserWriter.h"
#include "java/io/IOException.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ARUpdateMessageReceived () {
 @public
  ARApiPeer *peer_;
  jlong startDate_;
  jlong receivedDate_;
}

@end

J2OBJC_FIELD_SETTER(ARUpdateMessageReceived, peer_, ARApiPeer *)

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/updates/UpdateMessageReceived.java"


#line 18
@implementation ARUpdateMessageReceived

+ (jint)HEADER {
  return ARUpdateMessageReceived_HEADER;
}


#line 21
+ (ARUpdateMessageReceived *)fromBytesWithByteArray:(IOSByteArray *)data {
  return ARUpdateMessageReceived_fromBytesWithByteArray_(data);
}


#line 29
- (instancetype)initWithARApiPeer:(ARApiPeer *)peer
                         withLong:(jlong)startDate
                         withLong:(jlong)receivedDate {
  ARUpdateMessageReceived_initWithARApiPeer_withLong_withLong_(self, peer, startDate, receivedDate);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 35
- (instancetype)init {
  ARUpdateMessageReceived_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 40
- (ARApiPeer *)getPeer {
  return self->peer_;
}

- (jlong)getStartDate {
  return self->startDate_;
}

- (jlong)getReceivedDate {
  return self->receivedDate_;
}


#line 53
- (void)parseWithARBserValues:(ARBserValues *)values {
  self->peer_ = [((ARBserValues *) nil_chk(values)) getObjWithInt:1 withARBserObject:new_ARApiPeer_init()];
  self->startDate_ = [values getLongWithInt:2];
  self->receivedDate_ = [values getLongWithInt:3];
}


#line 60
- (void)serializeWithARBserWriter:(ARBserWriter *)writer {
  if (self->peer_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [((ARBserWriter *) nil_chk(writer)) writeObjectWithInt:1 withARBserObject:self->peer_];
  [writer writeLongWithInt:2 withLong:self->startDate_];
  [writer writeLongWithInt:3 withLong:self->receivedDate_];
}


#line 70
- (NSString *)description {
  NSString *res = @"update MessageReceived{";
  (void) JreStrAppendStrong(&res, "$@", @"peer=", self->peer_);
  (void) JreStrAppendStrong(&res, "$J", @", startDate=", self->startDate_);
  (void) JreStrAppendStrong(&res, "$J", @", receivedDate=", self->receivedDate_);
  (void) JreStrAppendStrong(&res, "$", @"}");
  return res;
}


#line 80
- (jint)getHeaderKey {
  return ARUpdateMessageReceived_HEADER;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "fromBytesWithByteArray:", "fromBytes", "Lim.actor.core.api.updates.UpdateMessageReceived;", 0x9, "Ljava.io.IOException;", NULL },
    { "initWithARApiPeer:withLong:withLong:", "UpdateMessageReceived", NULL, 0x1, NULL, NULL },
    { "init", "UpdateMessageReceived", NULL, 0x1, NULL, NULL },
    { "getPeer", NULL, "Lim.actor.core.api.ApiPeer;", 0x1, NULL, NULL },
    { "getStartDate", NULL, "J", 0x1, NULL, NULL },
    { "getReceivedDate", NULL, "J", 0x1, NULL, NULL },
    { "parseWithARBserValues:", "parse", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "serializeWithARBserWriter:", "serialize", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getHeaderKey", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "HEADER", "HEADER", 0x19, "I", NULL, NULL, .constantValue.asInt = ARUpdateMessageReceived_HEADER },
    { "peer_", NULL, 0x2, "Lim.actor.core.api.ApiPeer;", NULL, NULL, .constantValue.asLong = 0 },
    { "startDate_", NULL, 0x2, "J", NULL, NULL, .constantValue.asLong = 0 },
    { "receivedDate_", NULL, 0x2, "J", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ARUpdateMessageReceived = { 2, "UpdateMessageReceived", "im.actor.core.api.updates", NULL, 0x1, 10, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ARUpdateMessageReceived;
}

@end


#line 21
ARUpdateMessageReceived *ARUpdateMessageReceived_fromBytesWithByteArray_(IOSByteArray *data) {
  ARUpdateMessageReceived_initialize();
  
#line 22
  return ARBser_parseWithARBserObject_withByteArray_(new_ARUpdateMessageReceived_init(), data);
}


#line 29
void ARUpdateMessageReceived_initWithARApiPeer_withLong_withLong_(ARUpdateMessageReceived *self, ARApiPeer *peer, jlong startDate, jlong receivedDate) {
  (void) ACUpdate_init(self);
  
#line 30
  self->peer_ = peer;
  self->startDate_ = startDate;
  self->receivedDate_ = receivedDate;
}


#line 29
ARUpdateMessageReceived *new_ARUpdateMessageReceived_initWithARApiPeer_withLong_withLong_(ARApiPeer *peer, jlong startDate, jlong receivedDate) {
  ARUpdateMessageReceived *self = [ARUpdateMessageReceived alloc];
  ARUpdateMessageReceived_initWithARApiPeer_withLong_withLong_(self, peer, startDate, receivedDate);
  return self;
}

void ARUpdateMessageReceived_init(ARUpdateMessageReceived *self) {
  (void) ACUpdate_init(self);
}


#line 35
ARUpdateMessageReceived *new_ARUpdateMessageReceived_init() {
  ARUpdateMessageReceived *self = [ARUpdateMessageReceived alloc];
  ARUpdateMessageReceived_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ARUpdateMessageReceived)

#pragma clang diagnostic pop
