//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/updates/UpdateUserNickChanged.java
//

#ifndef _ImActorCoreApiUpdatesUpdateUserNickChanged_H_
#define _ImActorCoreApiUpdatesUpdateUserNickChanged_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/core/network/parser/Update.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#define ARUpdateUserNickChanged_HEADER 209

@interface ARUpdateUserNickChanged : ACUpdate

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)uid
               withNSString:(NSString *)nickname;

+ (ARUpdateUserNickChanged *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (NSString *)getNickname;

- (jint)getUid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARUpdateUserNickChanged)

J2OBJC_STATIC_FIELD_GETTER(ARUpdateUserNickChanged, HEADER, jint)

FOUNDATION_EXPORT ARUpdateUserNickChanged *ARUpdateUserNickChanged_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARUpdateUserNickChanged_initWithInt_withNSString_(ARUpdateUserNickChanged *self, jint uid, NSString *nickname);

FOUNDATION_EXPORT ARUpdateUserNickChanged *new_ARUpdateUserNickChanged_initWithInt_withNSString_(jint uid, NSString *nickname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARUpdateUserNickChanged_init(ARUpdateUserNickChanged *self);

FOUNDATION_EXPORT ARUpdateUserNickChanged *new_ARUpdateUserNickChanged_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARUpdateUserNickChanged)

@compatibility_alias ImActorCoreApiUpdatesUpdateUserNickChanged ARUpdateUserNickChanged;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiUpdatesUpdateUserNickChanged_H_
