//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/i18n/LocaleLoader.java
//

#ifndef _ImActorCoreI18nLocaleLoader_H_
#define _ImActorCoreI18nLocaleLoader_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>

@class IOSObjectArray;
@class JavaUtilHashMap;

@interface ACLocaleLoader : NSObject

#pragma mark Public

- (instancetype)init;

+ (JavaUtilHashMap *)loadPropertiesFileWithNSString:(NSString *)name;

#pragma mark Package-Private

+ (IOSObjectArray *)linesWorkaroundWithNSString:(NSString *)s;

+ (IOSObjectArray *)valuesWorkaroundWithNSString:(NSString *)s;

@end

J2OBJC_EMPTY_STATIC_INIT(ACLocaleLoader)

FOUNDATION_EXPORT JavaUtilHashMap *ACLocaleLoader_loadPropertiesFileWithNSString_(NSString *name);

FOUNDATION_EXPORT IOSObjectArray *ACLocaleLoader_linesWorkaroundWithNSString_(NSString *s);

FOUNDATION_EXPORT IOSObjectArray *ACLocaleLoader_valuesWorkaroundWithNSString_(NSString *s);

FOUNDATION_EXPORT void ACLocaleLoader_init(ACLocaleLoader *self);

FOUNDATION_EXPORT ACLocaleLoader *new_ACLocaleLoader_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACLocaleLoader)

@compatibility_alias ImActorCoreI18nLocaleLoader ACLocaleLoader;


#pragma clang diagnostic pop
#endif // _ImActorCoreI18nLocaleLoader_H_
