//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/internal/notifications/entity/PendingNotification.java
//

#ifndef _ImActorCoreModulesInternalNotificationsEntityPendingNotification_H_
#define _ImActorCoreModulesInternalNotificationsEntityPendingNotification_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/runtime/bser/BserObject.h>

@class ACContentDescription;
@class ACPeer;
@class ARBserValues;
@class ARBserWriter;

@interface ACPendingNotification : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithACPeer:(ACPeer *)peer
                       withInt:(jint)sender
                      withLong:(jlong)date
      withACContentDescription:(ACContentDescription *)content;

- (ACContentDescription *)getContent;

- (jlong)getDate;

- (ACPeer *)getPeer;

- (jint)getSender;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPendingNotification)

FOUNDATION_EXPORT void ACPendingNotification_initWithACPeer_withInt_withLong_withACContentDescription_(ACPendingNotification *self, ACPeer *peer, jint sender, jlong date, ACContentDescription *content);

FOUNDATION_EXPORT ACPendingNotification *new_ACPendingNotification_initWithACPeer_withInt_withLong_withACContentDescription_(ACPeer *peer, jint sender, jlong date, ACContentDescription *content) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ACPendingNotification_init(ACPendingNotification *self);

FOUNDATION_EXPORT ACPendingNotification *new_ACPendingNotification_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACPendingNotification)

@compatibility_alias ImActorCoreModulesInternalNotificationsEntityPendingNotification ACPendingNotification;


#pragma clang diagnostic pop
#endif // _ImActorCoreModulesInternalNotificationsEntityPendingNotification_H_
