//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/viewmodel/generics/ArrayListDialogSmall.java
//

#ifndef _ImActorCoreViewmodelGenericsArrayListDialogSmall_H_
#define _ImActorCoreViewmodelGenericsArrayListDialogSmall_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <j2objc/java/util/ArrayList.h>

@class ACDialogSmall;

@interface ACArrayListDialogSmall : JavaUtilArrayList

#pragma mark Public

- (instancetype)init;

- (ACDialogSmall *)getWithInt:(jint)index;

#pragma mark Package-Private


@end

J2OBJC_EMPTY_STATIC_INIT(ACArrayListDialogSmall)

FOUNDATION_EXPORT void ACArrayListDialogSmall_init(ACArrayListDialogSmall *self);

FOUNDATION_EXPORT ACArrayListDialogSmall *new_ACArrayListDialogSmall_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACArrayListDialogSmall)

@compatibility_alias ImActorCoreViewmodelGenericsArrayListDialogSmall ACArrayListDialogSmall;


#pragma clang diagnostic pop
#endif // _ImActorCoreViewmodelGenericsArrayListDialogSmall_H_
