//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/entity/content/PhotoContent.java
//

#ifndef _ImActorCoreEntityContentPhotoContent_H_
#define _ImActorCoreEntityContentPhotoContent_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/core/entity/content/DocumentContent.h>

@class ACContentLocalContainer;
@class ACContentRemoteContainer;
@class ACFastThumb;
@class ACFileReference;

@interface ACPhotoContent : ACDocumentContent

#pragma mark Public

- (instancetype)initWithACContentLocalContainer:(ACContentLocalContainer *)contentLocalContainer;

- (instancetype)initWithACContentRemoteContainer:(ACContentRemoteContainer *)contentRemoteContainer;

+ (ACPhotoContent *)createLocalPhotoWithNSString:(NSString *)descriptor
                                    withNSString:(NSString *)fileName
                                         withInt:(jint)fileSize
                                         withInt:(jint)w
                                         withInt:(jint)h
                                 withACFastThumb:(ACFastThumb *)fastThumb;

+ (ACPhotoContent *)createRemotePhotoWithACFileReference:(ACFileReference *)reference
                                                 withInt:(jint)w
                                                 withInt:(jint)h
                                         withACFastThumb:(ACFastThumb *)fastThumb;

- (jint)getH;

- (jint)getW;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPhotoContent)

FOUNDATION_EXPORT ACPhotoContent *ACPhotoContent_createLocalPhotoWithNSString_withNSString_withInt_withInt_withInt_withACFastThumb_(NSString *descriptor, NSString *fileName, jint fileSize, jint w, jint h, ACFastThumb *fastThumb);

FOUNDATION_EXPORT ACPhotoContent *ACPhotoContent_createRemotePhotoWithACFileReference_withInt_withInt_withACFastThumb_(ACFileReference *reference, jint w, jint h, ACFastThumb *fastThumb);

FOUNDATION_EXPORT void ACPhotoContent_initWithACContentLocalContainer_(ACPhotoContent *self, ACContentLocalContainer *contentLocalContainer);

FOUNDATION_EXPORT ACPhotoContent *new_ACPhotoContent_initWithACContentLocalContainer_(ACContentLocalContainer *contentLocalContainer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ACPhotoContent_initWithACContentRemoteContainer_(ACPhotoContent *self, ACContentRemoteContainer *contentRemoteContainer);

FOUNDATION_EXPORT ACPhotoContent *new_ACPhotoContent_initWithACContentRemoteContainer_(ACContentRemoteContainer *contentRemoteContainer) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACPhotoContent)

@compatibility_alias ImActorCoreEntityContentPhotoContent ACPhotoContent;


#pragma clang diagnostic pop
#endif // _ImActorCoreEntityContentPhotoContent_H_
