//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/internal/AppStateModule.java
//

#include <j2objc/IOSClass.h>
#include <j2objc/J2ObjC_source.h>
#include "im/actor/core/api/ApiAppCounters.h"
#include "im/actor/core/modules/AbsModule.h"
#include "im/actor/core/modules/ModuleContext.h"
#include "im/actor/core/modules/internal/AppStateModule.h"
#include "im/actor/core/modules/internal/state/ListsStatesActor.h"
#include "im/actor/core/viewmodel/AppStateVM.h"
#include "im/actor/runtime/actors/ActorCreator.h"
#include "im/actor/runtime/actors/ActorRef.h"
#include "im/actor/runtime/actors/ActorSystem.h"
#include "im/actor/runtime/actors/Props.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ACAppStateModule () {
 @public
  ACAppStateVM *appStateVM_;
  ARActorRef *listStatesActor_;
}

@end

J2OBJC_FIELD_SETTER(ACAppStateModule, appStateVM_, ACAppStateVM *)
J2OBJC_FIELD_SETTER(ACAppStateModule, listStatesActor_, ARActorRef *)

@interface ACAppStateModule_$1 : NSObject < ARActorCreator > {
 @public
  ACAppStateModule *this$0_;
}

- (ACListsStatesActor *)create;

- (instancetype)initWithACAppStateModule:(ACAppStateModule *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ACAppStateModule_$1)

J2OBJC_FIELD_SETTER(ACAppStateModule_$1, this$0_, ACAppStateModule *)

__attribute__((unused)) static void ACAppStateModule_$1_initWithACAppStateModule_(ACAppStateModule_$1 *self, ACAppStateModule *outer$);

__attribute__((unused)) static ACAppStateModule_$1 *new_ACAppStateModule_$1_initWithACAppStateModule_(ACAppStateModule *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACAppStateModule_$1)

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/internal/AppStateModule.java"


#line 18
@implementation ACAppStateModule


#line 22
- (instancetype)initWithACModuleContext:(id<ACModuleContext>)context {
  ACAppStateModule_initWithACModuleContext_(self, context);
  return self;
}

- (void)run {
  listStatesActor_ = [((ARActorSystem *) nil_chk(ARActorSystem_system())) actorOfWithARProps:ARProps_createWithIOSClass_withARActorCreator_(ACListsStatesActor_class_(), new_ACAppStateModule_$1_initWithACAppStateModule_(self)) withNSString:
#line 33
  @"actor/app/state"];
}


#line 36
- (void)onDialogsUpdateWithBoolean:(jboolean)isEmpty {
  [((ARActorRef *) nil_chk(listStatesActor_)) sendWithId:new_ACListsStatesActor_OnDialogsChanged_initWithBoolean_(isEmpty)];
}

- (void)onContactsUpdateWithBoolean:(jboolean)isEmpty {
  [((ARActorRef *) nil_chk(listStatesActor_)) sendWithId:new_ACListsStatesActor_OnContactsChanged_initWithBoolean_(isEmpty)];
}

- (void)onBookImported {
  [((ARActorRef *) nil_chk(listStatesActor_)) sendWithId:new_ACListsStatesActor_OnBookImported_init()];
}

- (void)onContactsLoaded {
  [((ARActorRef *) nil_chk(listStatesActor_)) sendWithId:new_ACListsStatesActor_OnContactsLoaded_init()];
}

- (void)onDialogsLoaded {
  [((ARActorRef *) nil_chk(listStatesActor_)) sendWithId:new_ACListsStatesActor_OnDialogsLoaded_init()];
}

- (void)onCountersChangedWithARApiAppCounters:(ARApiAppCounters *)counters {
  [((ARActorRef *) nil_chk(listStatesActor_)) sendWithId:new_ACListsStatesActor_OnAppCounterChanged_initWithARApiAppCounters_(counters)];
}

- (ACAppStateVM *)getAppStateVM {
  return appStateVM_;
}

- (void)resetModule {
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithACModuleContext:", "AppStateModule", NULL, 0x1, NULL, NULL },
    { "run", NULL, "V", 0x1, NULL, NULL },
    { "onDialogsUpdateWithBoolean:", "onDialogsUpdate", "V", 0x1, NULL, NULL },
    { "onContactsUpdateWithBoolean:", "onContactsUpdate", "V", 0x1, NULL, NULL },
    { "onBookImported", NULL, "V", 0x1, NULL, NULL },
    { "onContactsLoaded", NULL, "V", 0x1, NULL, NULL },
    { "onDialogsLoaded", NULL, "V", 0x1, NULL, NULL },
    { "onCountersChangedWithARApiAppCounters:", "onCountersChanged", "V", 0x1, NULL, NULL },
    { "getAppStateVM", NULL, "Lim.actor.core.viewmodel.AppStateVM;", 0x1, NULL, NULL },
    { "resetModule", NULL, "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "appStateVM_", NULL, 0x2, "Lim.actor.core.viewmodel.AppStateVM;", NULL, NULL, .constantValue.asLong = 0 },
    { "listStatesActor_", NULL, 0x2, "Lim.actor.runtime.actors.ActorRef;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ACAppStateModule = { 2, "AppStateModule", "im.actor.core.modules.internal", NULL, 0x1, 10, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ACAppStateModule;
}

@end


#line 22
void ACAppStateModule_initWithACModuleContext_(ACAppStateModule *self, id<ACModuleContext> context) {
  (void) ACAbsModule_initWithACModuleContext_(self, context);
  self->appStateVM_ = new_ACAppStateVM_initWithACModuleContext_(context);
}


#line 22
ACAppStateModule *new_ACAppStateModule_initWithACModuleContext_(id<ACModuleContext> context) {
  ACAppStateModule *self = [ACAppStateModule alloc];
  ACAppStateModule_initWithACModuleContext_(self, context);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ACAppStateModule)

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/internal/AppStateModule.java"

@implementation ACAppStateModule_$1


#line 30
- (ACListsStatesActor *)create {
  return new_ACListsStatesActor_initWithACModuleContext_([this$0_ context]);
}

- (instancetype)initWithACAppStateModule:(ACAppStateModule *)outer$ {
  ACAppStateModule_$1_initWithACAppStateModule_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "create", NULL, "Lim.actor.core.modules.internal.state.ListsStatesActor;", 0x1, NULL, NULL },
    { "initWithACAppStateModule:", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lim.actor.core.modules.internal.AppStateModule;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ACAppStateModule", "run" };
  static const J2ObjcClassInfo _ACAppStateModule_$1 = { 2, "", "im.actor.core.modules.internal", "AppStateModule", 0x8008, 2, methods, 1, fields, 0, NULL, 0, NULL, &enclosing_method, "Ljava/lang/Object;Lim/actor/runtime/actors/ActorCreator<Lim/actor/core/modules/internal/state/ListsStatesActor;>;" };
  return &_ACAppStateModule_$1;
}

@end

void ACAppStateModule_$1_initWithACAppStateModule_(ACAppStateModule_$1 *self, ACAppStateModule *outer$) {
  self->this$0_ = outer$;
  (void) NSObject_init(self);
}

ACAppStateModule_$1 *new_ACAppStateModule_$1_initWithACAppStateModule_(ACAppStateModule *outer$) {
  ACAppStateModule_$1 *self = [ACAppStateModule_$1 alloc];
  ACAppStateModule_$1_initWithACAppStateModule_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ACAppStateModule_$1)

#pragma clang diagnostic pop
