//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//im/actor/runtime/actors/dispatch/QueueListener.java
//

#ifndef _ImActorRuntimeActorsDispatchQueueListener_H_
#define _ImActorRuntimeActorsDispatchQueueListener_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>

/*!
 @brief Listener for monitoring queue changes in dispatchers
 */
@protocol ImActorRuntimeActorsDispatchQueueListener < NSObject, JavaObject >

- (void)onQueueChanged;

@end

J2OBJC_EMPTY_STATIC_INIT(ImActorRuntimeActorsDispatchQueueListener)

J2OBJC_TYPE_LITERAL_HEADER(ImActorRuntimeActorsDispatchQueueListener)


#pragma clang diagnostic pop
#endif // _ImActorRuntimeActorsDispatchQueueListener_H_
