//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/network/parser/Response.java
//

#ifndef _ImActorCoreNetworkParserResponse_H_
#define _ImActorCoreNetworkParserResponse_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/core/network/parser/RpcScope.h"

@interface ACResponse : ACRpcScope

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ACResponse)

FOUNDATION_EXPORT void ACResponse_init(ACResponse *self);

J2OBJC_TYPE_LITERAL_HEADER(ACResponse)

@compatibility_alias ImActorCoreNetworkParserResponse ACResponse;


#pragma clang diagnostic pop
#endif // _ImActorCoreNetworkParserResponse_H_
