//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//org/bouncycastle/crypto/digests/GeneralDigest.java
//

#ifndef _OrgBouncycastleCryptoDigestsGeneralDigest_H_
#define _OrgBouncycastleCryptoDigestsGeneralDigest_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/org/bouncycastle/crypto/ExtendedDigest.h>
#include <ActorSDK/org/bouncycastle/util/Memoable.h>

@class IOSByteArray;

/*!
 @brief base implementation of MD4 family style digest as outlined in
 "Handbook of Applied Cryptography", pages 344 - 347.
 */
@interface OrgBouncycastleCryptoDigestsGeneralDigest : NSObject < OrgBouncycastleCryptoExtendedDigest, OrgBouncycastleUtilMemoable >

#pragma mark Public

- (void)finish;

- (jint)getByteLength;

- (void)reset;

- (void)updateWithByte:(jbyte)inArg;

- (void)updateWithByteArray:(IOSByteArray *)inArg
                    withInt:(jint)inOff
                    withInt:(jint)len;

#pragma mark Protected

/*!
 @brief Standard constructor
 */
- (instancetype)init;

- (instancetype)initWithByteArray:(IOSByteArray *)encodedState;

/*!
 @brief Copy constructor.
 We are using copy constructors in place
 of the Object.clone() interface as this interface is not
 supported by J2ME.
 */
- (instancetype)initWithOrgBouncycastleCryptoDigestsGeneralDigest:(OrgBouncycastleCryptoDigestsGeneralDigest *)t;

- (void)copyInWithOrgBouncycastleCryptoDigestsGeneralDigest:(OrgBouncycastleCryptoDigestsGeneralDigest *)t OBJC_METHOD_FAMILY_NONE;

- (void)populateStateWithByteArray:(IOSByteArray *)state;

- (void)processBlock;

- (void)processLengthWithLong:(jlong)bitLength;

- (void)processWordWithByteArray:(IOSByteArray *)inArg
                         withInt:(jint)inOff;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgBouncycastleCryptoDigestsGeneralDigest)

FOUNDATION_EXPORT void OrgBouncycastleCryptoDigestsGeneralDigest_init(OrgBouncycastleCryptoDigestsGeneralDigest *self);

FOUNDATION_EXPORT void OrgBouncycastleCryptoDigestsGeneralDigest_initWithOrgBouncycastleCryptoDigestsGeneralDigest_(OrgBouncycastleCryptoDigestsGeneralDigest *self, OrgBouncycastleCryptoDigestsGeneralDigest *t);

FOUNDATION_EXPORT void OrgBouncycastleCryptoDigestsGeneralDigest_initWithByteArray_(OrgBouncycastleCryptoDigestsGeneralDigest *self, IOSByteArray *encodedState);

J2OBJC_TYPE_LITERAL_HEADER(OrgBouncycastleCryptoDigestsGeneralDigest)


#pragma clang diagnostic pop
#endif // _OrgBouncycastleCryptoDigestsGeneralDigest_H_
