//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//im/actor/runtime/mvvm/AsyncVM.java
//

#ifndef _ImActorRuntimeMvvmAsyncVM_H_
#define _ImActorRuntimeMvvmAsyncVM_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>

@interface ARAsyncVM : NSObject

#pragma mark Public

- (instancetype)init;

- (void)detach;

#pragma mark Protected

- (void)onObjectReceivedWithId:(id)obj;

- (void)postWithId:(id)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(ARAsyncVM)

FOUNDATION_EXPORT void ARAsyncVM_init(ARAsyncVM *self);

J2OBJC_TYPE_LITERAL_HEADER(ARAsyncVM)

@compatibility_alias ImActorRuntimeMvvmAsyncVM ARAsyncVM;


#pragma clang diagnostic pop
#endif // _ImActorRuntimeMvvmAsyncVM_H_
