//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//im/actor/runtime/mvvm/ValueModelCreator.java
//

#include <j2objc/J2ObjC_source.h>
#include "im/actor/runtime/mvvm/BaseValueModel.h"
#include "im/actor/runtime/mvvm/ValueModelCreator.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ARValueModelCreator : NSObject

@end

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//im/actor/runtime/mvvm/ValueModelCreator.java"


#line 3
@implementation ARValueModelCreator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createWithId:", "create", "TV;", 0x401, NULL, "(TT;)TV;" },
  };
  static const J2ObjcClassInfo _ARValueModelCreator = { 2, "ValueModelCreator", "im.actor.runtime.mvvm", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;V:Lim/actor/runtime/mvvm/BaseValueModel<TT;>;>Ljava/lang/Object;" };
  return &_ARValueModelCreator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ARValueModelCreator)

#pragma clang diagnostic pop
