//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/RequestTerminateSession.java
//

#ifndef _ImActorCoreApiRpcRequestTerminateSession_H_
#define _ImActorCoreApiRpcRequestTerminateSession_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#define ARRequestTerminateSession_HEADER 82

@interface ARRequestTerminateSession : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)id_;

+ (ARRequestTerminateSession *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (jint)getId;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestTerminateSession)

J2OBJC_STATIC_FIELD_GETTER(ARRequestTerminateSession, HEADER, jint)

FOUNDATION_EXPORT ARRequestTerminateSession *ARRequestTerminateSession_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestTerminateSession_initWithInt_(ARRequestTerminateSession *self, jint id_);

FOUNDATION_EXPORT ARRequestTerminateSession *new_ARRequestTerminateSession_initWithInt_(jint id_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARRequestTerminateSession_init(ARRequestTerminateSession *self);

FOUNDATION_EXPORT ARRequestTerminateSession *new_ARRequestTerminateSession_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARRequestTerminateSession)

@compatibility_alias ImActorCoreApiRpcRequestTerminateSession ARRequestTerminateSession;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiRpcRequestTerminateSession_H_
