//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/RequestLoadDialogs.java
//

#ifndef _ImActorCoreApiRpcRequestLoadDialogs_H_
#define _ImActorCoreApiRpcRequestLoadDialogs_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/core/network/parser/Request.h"

@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#define ARRequestLoadDialogs_HEADER 104

@interface ARRequestLoadDialogs : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)minDate
                     withInt:(jint)limit;

+ (ARRequestLoadDialogs *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (jint)getLimit;

- (jlong)getMinDate;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestLoadDialogs)

J2OBJC_STATIC_FIELD_GETTER(ARRequestLoadDialogs, HEADER, jint)

FOUNDATION_EXPORT ARRequestLoadDialogs *ARRequestLoadDialogs_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestLoadDialogs_initWithLong_withInt_(ARRequestLoadDialogs *self, jlong minDate, jint limit);

FOUNDATION_EXPORT ARRequestLoadDialogs *new_ARRequestLoadDialogs_initWithLong_withInt_(jlong minDate, jint limit) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARRequestLoadDialogs_init(ARRequestLoadDialogs *self);

FOUNDATION_EXPORT ARRequestLoadDialogs *new_ARRequestLoadDialogs_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARRequestLoadDialogs)

@compatibility_alias ImActorCoreApiRpcRequestLoadDialogs ARRequestLoadDialogs;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiRpcRequestLoadDialogs_H_
