//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/RequestEditGroupAvatar.java
//

#ifndef _ImActorCoreApiRpcRequestEditGroupAvatar_H_
#define _ImActorCoreApiRpcRequestEditGroupAvatar_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/core/network/parser/Request.h>

@class ARApiFileLocation;
@class ARApiGroupOutPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#define ARRequestEditGroupAvatar_HEADER 86

@interface ARRequestEditGroupAvatar : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiGroupOutPeer:(ARApiGroupOutPeer *)groupPeer
                                 withLong:(jlong)rid
                    withARApiFileLocation:(ARApiFileLocation *)fileLocation;

+ (ARRequestEditGroupAvatar *)fromBytesWithByteArray:(IOSByteArray *)data;

- (ARApiFileLocation *)getFileLocation;

- (ARApiGroupOutPeer *)getGroupPeer;

- (jint)getHeaderKey;

- (jlong)getRid;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestEditGroupAvatar)

J2OBJC_STATIC_FIELD_GETTER(ARRequestEditGroupAvatar, HEADER, jint)

FOUNDATION_EXPORT ARRequestEditGroupAvatar *ARRequestEditGroupAvatar_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestEditGroupAvatar_initWithARApiGroupOutPeer_withLong_withARApiFileLocation_(ARRequestEditGroupAvatar *self, ARApiGroupOutPeer *groupPeer, jlong rid, ARApiFileLocation *fileLocation);

FOUNDATION_EXPORT ARRequestEditGroupAvatar *new_ARRequestEditGroupAvatar_initWithARApiGroupOutPeer_withLong_withARApiFileLocation_(ARApiGroupOutPeer *groupPeer, jlong rid, ARApiFileLocation *fileLocation) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARRequestEditGroupAvatar_init(ARRequestEditGroupAvatar *self);

FOUNDATION_EXPORT ARRequestEditGroupAvatar *new_ARRequestEditGroupAvatar_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARRequestEditGroupAvatar)

@compatibility_alias ImActorCoreApiRpcRequestEditGroupAvatar ARRequestEditGroupAvatar;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiRpcRequestEditGroupAvatar_H_
