//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/RequestCreateGroup.java
//

#include <j2objc/IOSClass.h>
#include <j2objc/IOSPrimitiveArray.h>
#include <j2objc/J2ObjC_source.h>
#include "im/actor/core/api/ApiUserOutPeer.h"
#include "im/actor/core/api/rpc/RequestCreateGroup.h"
#include "im/actor/core/network/parser/Request.h"
#include "im/actor/runtime/bser/Bser.h"
#include "im/actor/runtime/bser/BserObject.h"
#include "im/actor/runtime/bser/BserValues.h"
#include "im/actor/runtime/bser/BserWriter.h"
#include <j2objc/java/io/IOException.h>
#include <j2objc/java/util/ArrayList.h>
#include <j2objc/java/util/List.h>

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ARRequestCreateGroup () {
 @public
  jlong rid_;
  NSString *title_;
  id<JavaUtilList> users_;
}

@end

J2OBJC_FIELD_SETTER(ARRequestCreateGroup, title_, NSString *)
J2OBJC_FIELD_SETTER(ARRequestCreateGroup, users_, id<JavaUtilList>)

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/RequestCreateGroup.java"


#line 18
@implementation ARRequestCreateGroup

+ (jint)HEADER {
  return ARRequestCreateGroup_HEADER;
}


#line 21
+ (ARRequestCreateGroup *)fromBytesWithByteArray:(IOSByteArray *)data {
  return ARRequestCreateGroup_fromBytesWithByteArray_(data);
}


#line 29
- (instancetype)initWithLong:(jlong)rid
                withNSString:(NSString *)title
            withJavaUtilList:(id<JavaUtilList>)users {
  ARRequestCreateGroup_initWithLong_withNSString_withJavaUtilList_(self, rid, title, users);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 35
- (instancetype)init {
  ARRequestCreateGroup_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 39
- (jlong)getRid {
  return self->rid_;
}


#line 44
- (NSString *)getTitle {
  return self->title_;
}


#line 49
- (id<JavaUtilList>)getUsers {
  return self->users_;
}


#line 54
- (void)parseWithARBserValues:(ARBserValues *)values {
  self->rid_ = [((ARBserValues *) nil_chk(values)) getLongWithInt:1];
  self->title_ = [values getStringWithInt:2];
  id<JavaUtilList> _users = new_JavaUtilArrayList_init();
  for (jint i = 0; i < [values getRepeatedCountWithInt:3]; i++) {
    [_users addWithId:new_ARApiUserOutPeer_init()];
  }
  self->users_ = [values getRepeatedObjWithInt:3 withJavaUtilList:_users];
}


#line 65
- (void)serializeWithARBserWriter:(ARBserWriter *)writer {
  [((ARBserWriter *) nil_chk(writer)) writeLongWithInt:1 withLong:self->rid_];
  if (self->title_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [writer writeStringWithInt:2 withNSString:self->title_];
  [writer writeRepeatedObjWithInt:3 withJavaUtilList:self->users_];
}


#line 75
- (NSString *)description {
  NSString *res = @"rpc CreateGroup{";
  (void) JreStrAppendStrong(&res, "$J", @"rid=", self->rid_);
  (void) JreStrAppendStrong(&res, "$$", @", title=", self->title_);
  (void) JreStrAppendStrong(&res, "$I", @", users=", [((id<JavaUtilList>) nil_chk(self->users_)) size]);
  (void) JreStrAppendStrong(&res, "$", @"}");
  return res;
}


#line 85
- (jint)getHeaderKey {
  return ARRequestCreateGroup_HEADER;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "fromBytesWithByteArray:", "fromBytes", "Lim.actor.core.api.rpc.RequestCreateGroup;", 0x9, "Ljava.io.IOException;", NULL },
    { "initWithLong:withNSString:withJavaUtilList:", "RequestCreateGroup", NULL, 0x1, NULL, NULL },
    { "init", "RequestCreateGroup", NULL, 0x1, NULL, NULL },
    { "getRid", NULL, "J", 0x1, NULL, NULL },
    { "getTitle", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getUsers", NULL, "Ljava.util.List;", 0x1, NULL, NULL },
    { "parseWithARBserValues:", "parse", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "serializeWithARBserWriter:", "serialize", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getHeaderKey", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "HEADER", "HEADER", 0x19, "I", NULL, NULL, .constantValue.asInt = ARRequestCreateGroup_HEADER },
    { "rid_", NULL, 0x2, "J", NULL, NULL, .constantValue.asLong = 0 },
    { "title_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "users_", NULL, 0x2, "Ljava.util.List;", NULL, "Ljava/util/List<Lim/actor/core/api/ApiUserOutPeer;>;", .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lim.actor.core.api.rpc.ResponseCreateGroup;"};
  static const J2ObjcClassInfo _ARRequestCreateGroup = { 2, "RequestCreateGroup", "im.actor.core.api.rpc", NULL, 0x1, 10, methods, 4, fields, 1, superclass_type_args, 0, NULL, NULL, "Lim/actor/core/network/parser/Request<Lim/actor/core/api/rpc/ResponseCreateGroup;>;" };
  return &_ARRequestCreateGroup;
}

@end


#line 21
ARRequestCreateGroup *ARRequestCreateGroup_fromBytesWithByteArray_(IOSByteArray *data) {
  ARRequestCreateGroup_initialize();
  
#line 22
  return ARBser_parseWithARBserObject_withByteArray_(new_ARRequestCreateGroup_init(), data);
}


#line 29
void ARRequestCreateGroup_initWithLong_withNSString_withJavaUtilList_(ARRequestCreateGroup *self, jlong rid, NSString *title, id<JavaUtilList> users) {
  (void) ACRequest_init(self);
  
#line 30
  self->rid_ = rid;
  self->title_ = title;
  self->users_ = users;
}


#line 29
ARRequestCreateGroup *new_ARRequestCreateGroup_initWithLong_withNSString_withJavaUtilList_(jlong rid, NSString *title, id<JavaUtilList> users) {
  ARRequestCreateGroup *self = [ARRequestCreateGroup alloc];
  ARRequestCreateGroup_initWithLong_withNSString_withJavaUtilList_(self, rid, title, users);
  return self;
}

void ARRequestCreateGroup_init(ARRequestCreateGroup *self) {
  (void) ACRequest_init(self);
}


#line 35
ARRequestCreateGroup *new_ARRequestCreateGroup_init() {
  ARRequestCreateGroup *self = [ARRequestCreateGroup alloc];
  ARRequestCreateGroup_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ARRequestCreateGroup)

#pragma clang diagnostic pop
