//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/RequestEnterGroup.java
//

#ifndef _ImActorCoreApiRpcRequestEnterGroup_H_
#define _ImActorCoreApiRpcRequestEnterGroup_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/core/network/parser/Request.h>

@class ARApiGroupOutPeer;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#define ARRequestEnterGroup_HEADER 199

@interface ARRequestEnterGroup : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiGroupOutPeer:(ARApiGroupOutPeer *)peer;

+ (ARRequestEnterGroup *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jint)getHeaderKey;

- (ARApiGroupOutPeer *)getPeer;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestEnterGroup)

J2OBJC_STATIC_FIELD_GETTER(ARRequestEnterGroup, HEADER, jint)

FOUNDATION_EXPORT ARRequestEnterGroup *ARRequestEnterGroup_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestEnterGroup_initWithARApiGroupOutPeer_(ARRequestEnterGroup *self, ARApiGroupOutPeer *peer);

FOUNDATION_EXPORT ARRequestEnterGroup *new_ARRequestEnterGroup_initWithARApiGroupOutPeer_(ARApiGroupOutPeer *peer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARRequestEnterGroup_init(ARRequestEnterGroup *self);

FOUNDATION_EXPORT ARRequestEnterGroup *new_ARRequestEnterGroup_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARRequestEnterGroup)

@compatibility_alias ImActorCoreApiRpcRequestEnterGroup ARRequestEnterGroup;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiRpcRequestEnterGroup_H_
