//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/RequestInitWebaction.java
//

#ifndef _ImActorCoreApiRpcRequestInitWebaction_H_
#define _ImActorCoreApiRpcRequestInitWebaction_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/core/network/parser/Request.h"

@class ARApiMapValue;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;

#define ARRequestInitWebaction_HEADER 116

@interface ARRequestInitWebaction : ACRequest

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)actionName
               withARApiMapValue:(ARApiMapValue *)params;

+ (ARRequestInitWebaction *)fromBytesWithByteArray:(IOSByteArray *)data;

- (NSString *)getActionName;

- (jint)getHeaderKey;

- (ARApiMapValue *)getParams;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARRequestInitWebaction)

J2OBJC_STATIC_FIELD_GETTER(ARRequestInitWebaction, HEADER, jint)

FOUNDATION_EXPORT ARRequestInitWebaction *ARRequestInitWebaction_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARRequestInitWebaction_initWithNSString_withARApiMapValue_(ARRequestInitWebaction *self, NSString *actionName, ARApiMapValue *params);

FOUNDATION_EXPORT ARRequestInitWebaction *new_ARRequestInitWebaction_initWithNSString_withARApiMapValue_(NSString *actionName, ARApiMapValue *params) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARRequestInitWebaction_init(ARRequestInitWebaction *self);

FOUNDATION_EXPORT ARRequestInitWebaction *new_ARRequestInitWebaction_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARRequestInitWebaction)

@compatibility_alias ImActorCoreApiRpcRequestInitWebaction ARRequestInitWebaction;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiRpcRequestInitWebaction_H_
