//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/ResponseEnterGroup.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "im/actor/core/api/ApiGroup.h"
#include "im/actor/core/api/ApiUser.h"
#include "im/actor/core/api/rpc/ResponseEnterGroup.h"
#include "im/actor/core/network/parser/Response.h"
#include "im/actor/runtime/bser/Bser.h"
#include "im/actor/runtime/bser/BserObject.h"
#include "im/actor/runtime/bser/BserValues.h"
#include "im/actor/runtime/bser/BserWriter.h"
#include "java/io/IOException.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ARResponseEnterGroup () {
 @public
  ARApiGroup *group_;
  id<JavaUtilList> users_;
  jlong rid_;
  jint seq_;
  IOSByteArray *state_;
  jlong date_;
}

@end

J2OBJC_FIELD_SETTER(ARResponseEnterGroup, group_, ARApiGroup *)
J2OBJC_FIELD_SETTER(ARResponseEnterGroup, users_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ARResponseEnterGroup, state_, IOSByteArray *)

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/ResponseEnterGroup.java"


#line 18
@implementation ARResponseEnterGroup

+ (jint)HEADER {
  return ARResponseEnterGroup_HEADER;
}


#line 21
+ (ARResponseEnterGroup *)fromBytesWithByteArray:(IOSByteArray *)data {
  return ARResponseEnterGroup_fromBytesWithByteArray_(data);
}


#line 32
- (instancetype)initWithARApiGroup:(ARApiGroup *)group
                  withJavaUtilList:(id<JavaUtilList>)users
                          withLong:(jlong)rid
                           withInt:(jint)seq
                     withByteArray:(IOSByteArray *)state
                          withLong:(jlong)date {
  ARResponseEnterGroup_initWithARApiGroup_withJavaUtilList_withLong_withInt_withByteArray_withLong_(self, group, users, rid, seq, state, date);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 41
- (instancetype)init {
  ARResponseEnterGroup_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 46
- (ARApiGroup *)getGroup {
  return self->group_;
}


#line 51
- (id<JavaUtilList>)getUsers {
  return self->users_;
}

- (jlong)getRid {
  return self->rid_;
}

- (jint)getSeq {
  return self->seq_;
}


#line 64
- (IOSByteArray *)getState {
  return self->state_;
}

- (jlong)getDate {
  return self->date_;
}


#line 73
- (void)parseWithARBserValues:(ARBserValues *)values {
  self->group_ = [((ARBserValues *) nil_chk(values)) getObjWithInt:1 withARBserObject:new_ARApiGroup_init()];
  id<JavaUtilList> _users = new_JavaUtilArrayList_init();
  for (jint i = 0; i < [values getRepeatedCountWithInt:2]; i++) {
    [_users addWithId:new_ARApiUser_init()];
  }
  self->users_ = [values getRepeatedObjWithInt:2 withJavaUtilList:_users];
  self->rid_ = [values getLongWithInt:3];
  self->seq_ = [values getIntWithInt:4];
  self->state_ = [values getBytesWithInt:5];
  self->date_ = [values getLongWithInt:6];
}


#line 87
- (void)serializeWithARBserWriter:(ARBserWriter *)writer {
  if (self->group_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [((ARBserWriter *) nil_chk(writer)) writeObjectWithInt:1 withARBserObject:self->group_];
  [writer writeRepeatedObjWithInt:2 withJavaUtilList:self->users_];
  [writer writeLongWithInt:3 withLong:self->rid_];
  [writer writeIntWithInt:4 withInt:self->seq_];
  if (self->state_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [writer writeBytesWithInt:5 withByteArray:self->state_];
  [writer writeLongWithInt:6 withLong:self->date_];
}


#line 103
- (NSString *)description {
  NSString *res = @"tuple EnterGroup{";
  (void) JreStrAppendStrong(&res, "$", @"}");
  return res;
}


#line 110
- (jint)getHeaderKey {
  return ARResponseEnterGroup_HEADER;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "fromBytesWithByteArray:", "fromBytes", "Lim.actor.core.api.rpc.ResponseEnterGroup;", 0x9, "Ljava.io.IOException;", NULL },
    { "initWithARApiGroup:withJavaUtilList:withLong:withInt:withByteArray:withLong:", "ResponseEnterGroup", NULL, 0x1, NULL, NULL },
    { "init", "ResponseEnterGroup", NULL, 0x1, NULL, NULL },
    { "getGroup", NULL, "Lim.actor.core.api.ApiGroup;", 0x1, NULL, NULL },
    { "getUsers", NULL, "Ljava.util.List;", 0x1, NULL, NULL },
    { "getRid", NULL, "J", 0x1, NULL, NULL },
    { "getSeq", NULL, "I", 0x1, NULL, NULL },
    { "getState", NULL, "[B", 0x1, NULL, NULL },
    { "getDate", NULL, "J", 0x1, NULL, NULL },
    { "parseWithARBserValues:", "parse", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "serializeWithARBserWriter:", "serialize", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getHeaderKey", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "HEADER", "HEADER", 0x19, "I", NULL, NULL, .constantValue.asInt = ARResponseEnterGroup_HEADER },
    { "group_", NULL, 0x2, "Lim.actor.core.api.ApiGroup;", NULL, NULL, .constantValue.asLong = 0 },
    { "users_", NULL, 0x2, "Ljava.util.List;", NULL, "Ljava/util/List<Lim/actor/core/api/ApiUser;>;", .constantValue.asLong = 0 },
    { "rid_", NULL, 0x2, "J", NULL, NULL, .constantValue.asLong = 0 },
    { "seq_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "state_", NULL, 0x2, "[B", NULL, NULL, .constantValue.asLong = 0 },
    { "date_", NULL, 0x2, "J", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ARResponseEnterGroup = { 2, "ResponseEnterGroup", "im.actor.core.api.rpc", NULL, 0x1, 13, methods, 7, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ARResponseEnterGroup;
}

@end


#line 21
ARResponseEnterGroup *ARResponseEnterGroup_fromBytesWithByteArray_(IOSByteArray *data) {
  ARResponseEnterGroup_initialize();
  
#line 22
  return ARBser_parseWithARBserObject_withByteArray_(new_ARResponseEnterGroup_init(), data);
}


#line 32
void ARResponseEnterGroup_initWithARApiGroup_withJavaUtilList_withLong_withInt_withByteArray_withLong_(ARResponseEnterGroup *self, ARApiGroup *group, id<JavaUtilList> users, jlong rid, jint seq, IOSByteArray *state, jlong date) {
  (void) ACResponse_init(self);
  
#line 33
  self->group_ = group;
  self->users_ = users;
  self->rid_ = rid;
  self->seq_ = seq;
  self->state_ = state;
  self->date_ = date;
}


#line 32
ARResponseEnterGroup *new_ARResponseEnterGroup_initWithARApiGroup_withJavaUtilList_withLong_withInt_withByteArray_withLong_(ARApiGroup *group, id<JavaUtilList> users, jlong rid, jint seq, IOSByteArray *state, jlong date) {
  ARResponseEnterGroup *self = [ARResponseEnterGroup alloc];
  ARResponseEnterGroup_initWithARApiGroup_withJavaUtilList_withLong_withInt_withByteArray_withLong_(self, group, users, rid, seq, state, date);
  return self;
}


#line 41
void ARResponseEnterGroup_init(ARResponseEnterGroup *self) {
  (void) ACResponse_init(self);
}


#line 41
ARResponseEnterGroup *new_ARResponseEnterGroup_init() {
  ARResponseEnterGroup *self = [ARResponseEnterGroup alloc];
  ARResponseEnterGroup_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ARResponseEnterGroup)

#pragma clang diagnostic pop
