//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/ResponseJoinGroup.java
//

#ifndef _ImActorCoreApiRpcResponseJoinGroup_H_
#define _ImActorCoreApiRpcResponseJoinGroup_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/core/network/parser/Response.h>

@class ARApiGroup;
@class ARBserValues;
@class ARBserWriter;
@class IOSByteArray;
@protocol JavaUtilList;

#define ARResponseJoinGroup_HEADER 181

@interface ARResponseJoinGroup : ACResponse

+ (jint)HEADER;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiGroup:(ARApiGroup *)group
                  withJavaUtilList:(id<JavaUtilList>)users
                          withLong:(jlong)rid
                           withInt:(jint)seq
                     withByteArray:(IOSByteArray *)state
                          withLong:(jlong)date;

+ (ARResponseJoinGroup *)fromBytesWithByteArray:(IOSByteArray *)data;

- (jlong)getDate;

- (ARApiGroup *)getGroup;

- (jint)getHeaderKey;

- (jlong)getRid;

- (jint)getSeq;

- (IOSByteArray *)getState;

- (id<JavaUtilList>)getUsers;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARResponseJoinGroup)

J2OBJC_STATIC_FIELD_GETTER(ARResponseJoinGroup, HEADER, jint)

FOUNDATION_EXPORT ARResponseJoinGroup *ARResponseJoinGroup_fromBytesWithByteArray_(IOSByteArray *data);

FOUNDATION_EXPORT void ARResponseJoinGroup_initWithARApiGroup_withJavaUtilList_withLong_withInt_withByteArray_withLong_(ARResponseJoinGroup *self, ARApiGroup *group, id<JavaUtilList> users, jlong rid, jint seq, IOSByteArray *state, jlong date);

FOUNDATION_EXPORT ARResponseJoinGroup *new_ARResponseJoinGroup_initWithARApiGroup_withJavaUtilList_withLong_withInt_withByteArray_withLong_(ARApiGroup *group, id<JavaUtilList> users, jlong rid, jint seq, IOSByteArray *state, jlong date) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARResponseJoinGroup_init(ARResponseJoinGroup *self);

FOUNDATION_EXPORT ARResponseJoinGroup *new_ARResponseJoinGroup_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARResponseJoinGroup)

@compatibility_alias ImActorCoreApiRpcResponseJoinGroup ARResponseJoinGroup;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiRpcResponseJoinGroup_H_
