//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/ResponseGetFileUploadUrl.java
//

#include <j2objc/IOSClass.h>
#include <j2objc/IOSPrimitiveArray.h>
#include <j2objc/J2ObjC_source.h>
#include "im/actor/core/api/rpc/ResponseGetFileUploadUrl.h"
#include "im/actor/core/network/parser/Response.h"
#include "im/actor/runtime/bser/Bser.h"
#include "im/actor/runtime/bser/BserObject.h"
#include "im/actor/runtime/bser/BserValues.h"
#include "im/actor/runtime/bser/BserWriter.h"
#include <j2objc/java/io/IOException.h>

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ARResponseGetFileUploadUrl () {
 @public
  NSString *url_;
  IOSByteArray *uploadKey_;
}

@end

J2OBJC_FIELD_SETTER(ARResponseGetFileUploadUrl, url_, NSString *)
J2OBJC_FIELD_SETTER(ARResponseGetFileUploadUrl, uploadKey_, IOSByteArray *)

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/rpc/ResponseGetFileUploadUrl.java"


#line 18
@implementation ARResponseGetFileUploadUrl

+ (jint)HEADER {
  return ARResponseGetFileUploadUrl_HEADER;
}


#line 21
+ (ARResponseGetFileUploadUrl *)fromBytesWithByteArray:(IOSByteArray *)data {
  return ARResponseGetFileUploadUrl_fromBytesWithByteArray_(data);
}


#line 28
- (instancetype)initWithNSString:(NSString *)url
                   withByteArray:(IOSByteArray *)uploadKey {
  ARResponseGetFileUploadUrl_initWithNSString_withByteArray_(self, url, uploadKey);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 33
- (instancetype)init {
  ARResponseGetFileUploadUrl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 38
- (NSString *)getUrl {
  return self->url_;
}


#line 43
- (IOSByteArray *)getUploadKey {
  return self->uploadKey_;
}


#line 48
- (void)parseWithARBserValues:(ARBserValues *)values {
  self->url_ = [((ARBserValues *) nil_chk(values)) getStringWithInt:1];
  self->uploadKey_ = [values getBytesWithInt:2];
}


#line 54
- (void)serializeWithARBserWriter:(ARBserWriter *)writer {
  if (self->url_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [((ARBserWriter *) nil_chk(writer)) writeStringWithInt:1 withNSString:self->url_];
  if (self->uploadKey_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [writer writeBytesWithInt:2 withByteArray:self->uploadKey_];
}


#line 66
- (NSString *)description {
  NSString *res = @"tuple GetFileUploadUrl{";
  (void) JreStrAppendStrong(&res, "$", @"}");
  return res;
}


#line 73
- (jint)getHeaderKey {
  return ARResponseGetFileUploadUrl_HEADER;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "fromBytesWithByteArray:", "fromBytes", "Lim.actor.core.api.rpc.ResponseGetFileUploadUrl;", 0x9, "Ljava.io.IOException;", NULL },
    { "initWithNSString:withByteArray:", "ResponseGetFileUploadUrl", NULL, 0x1, NULL, NULL },
    { "init", "ResponseGetFileUploadUrl", NULL, 0x1, NULL, NULL },
    { "getUrl", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getUploadKey", NULL, "[B", 0x1, NULL, NULL },
    { "parseWithARBserValues:", "parse", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "serializeWithARBserWriter:", "serialize", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "getHeaderKey", NULL, "I", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "HEADER", "HEADER", 0x19, "I", NULL, NULL, .constantValue.asInt = ARResponseGetFileUploadUrl_HEADER },
    { "url_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "uploadKey_", NULL, 0x2, "[B", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ARResponseGetFileUploadUrl = { 2, "ResponseGetFileUploadUrl", "im.actor.core.api.rpc", NULL, 0x1, 9, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ARResponseGetFileUploadUrl;
}

@end


#line 21
ARResponseGetFileUploadUrl *ARResponseGetFileUploadUrl_fromBytesWithByteArray_(IOSByteArray *data) {
  ARResponseGetFileUploadUrl_initialize();
  
#line 22
  return ARBser_parseWithARBserObject_withByteArray_(new_ARResponseGetFileUploadUrl_init(), data);
}

void ARResponseGetFileUploadUrl_initWithNSString_withByteArray_(ARResponseGetFileUploadUrl *self, NSString *url, IOSByteArray *uploadKey) {
  (void) ACResponse_init(self);
  
#line 29
  self->url_ = url;
  self->uploadKey_ = uploadKey;
}


#line 28
ARResponseGetFileUploadUrl *new_ARResponseGetFileUploadUrl_initWithNSString_withByteArray_(NSString *url, IOSByteArray *uploadKey) {
  ARResponseGetFileUploadUrl *self = [ARResponseGetFileUploadUrl alloc];
  ARResponseGetFileUploadUrl_initWithNSString_withByteArray_(self, url, uploadKey);
  return self;
}


#line 33
void ARResponseGetFileUploadUrl_init(ARResponseGetFileUploadUrl *self) {
  (void) ACResponse_init(self);
}


#line 33
ARResponseGetFileUploadUrl *new_ARResponseGetFileUploadUrl_init() {
  ARResponseGetFileUploadUrl *self = [ARResponseGetFileUploadUrl alloc];
  ARResponseGetFileUploadUrl_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ARResponseGetFileUploadUrl)

#pragma clang diagnostic pop
