//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/internal/search/SearchActor.java
//

#ifndef _ImActorCoreModulesInternalSearchSearchActor_H_
#define _ImActorCoreModulesInternalSearchSearchActor_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/core/modules/utils/ModuleActor.h>

@class IOSIntArray;
@protocol ACModuleContext;
@protocol JavaUtilList;

@interface ACSearchActor : ACModuleActor

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)modules;

- (void)onReceiveWithId:(id)message;

- (void)preStart;

@end

J2OBJC_EMPTY_STATIC_INIT(ACSearchActor)

FOUNDATION_EXPORT void ACSearchActor_initWithACModuleContext_(ACSearchActor *self, id<ACModuleContext> modules);

FOUNDATION_EXPORT ACSearchActor *new_ACSearchActor_initWithACModuleContext_(id<ACModuleContext> modules) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACSearchActor)

@compatibility_alias ImActorCoreModulesInternalSearchSearchActor ACSearchActor;

@interface ACSearchActor_OnDialogsUpdated : NSObject

#pragma mark Public

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)dialogs;

- (id<JavaUtilList>)getDialogs;

@end

J2OBJC_EMPTY_STATIC_INIT(ACSearchActor_OnDialogsUpdated)

FOUNDATION_EXPORT void ACSearchActor_OnDialogsUpdated_initWithJavaUtilList_(ACSearchActor_OnDialogsUpdated *self, id<JavaUtilList> dialogs);

FOUNDATION_EXPORT ACSearchActor_OnDialogsUpdated *new_ACSearchActor_OnDialogsUpdated_initWithJavaUtilList_(id<JavaUtilList> dialogs) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACSearchActor_OnDialogsUpdated)

@interface ACSearchActor_OnContactsUpdated : NSObject

#pragma mark Public

- (instancetype)initWithIntArray:(IOSIntArray *)contactsList;

- (IOSIntArray *)getContactsList;

@end

J2OBJC_EMPTY_STATIC_INIT(ACSearchActor_OnContactsUpdated)

FOUNDATION_EXPORT void ACSearchActor_OnContactsUpdated_initWithIntArray_(ACSearchActor_OnContactsUpdated *self, IOSIntArray *contactsList);

FOUNDATION_EXPORT ACSearchActor_OnContactsUpdated *new_ACSearchActor_OnContactsUpdated_initWithIntArray_(IOSIntArray *contactsList) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACSearchActor_OnContactsUpdated)

@interface ACSearchActor_Clear : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ACSearchActor_Clear)

FOUNDATION_EXPORT void ACSearchActor_Clear_init(ACSearchActor_Clear *self);

FOUNDATION_EXPORT ACSearchActor_Clear *new_ACSearchActor_Clear_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACSearchActor_Clear)


#pragma clang diagnostic pop
#endif // _ImActorCoreModulesInternalSearchSearchActor_H_
