//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/AuthState.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "im/actor/core/AuthState.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

__attribute__((unused)) static void ACAuthStateEnum_initWithNSString_withInt_(ACAuthStateEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static ACAuthStateEnum *new_ACAuthStateEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/AuthState.java"

J2OBJC_INITIALIZED_DEFN(ACAuthStateEnum)

ACAuthStateEnum *ACAuthStateEnum_values_[9];


#line 10
@implementation ACAuthStateEnum

+ (ACAuthStateEnum *)AUTH_START {
  return ACAuthStateEnum_AUTH_START;
}

+ (ACAuthStateEnum *)AUTH_EMAIL {
  return ACAuthStateEnum_AUTH_EMAIL;
}

+ (ACAuthStateEnum *)AUTH_PHONE {
  return ACAuthStateEnum_AUTH_PHONE;
}

+ (ACAuthStateEnum *)CODE_VALIDATION_PHONE {
  return ACAuthStateEnum_CODE_VALIDATION_PHONE;
}

+ (ACAuthStateEnum *)CODE_VALIDATION_EMAIL {
  return ACAuthStateEnum_CODE_VALIDATION_EMAIL;
}

+ (ACAuthStateEnum *)GET_OAUTH_PARAMS {
  return ACAuthStateEnum_GET_OAUTH_PARAMS;
}

+ (ACAuthStateEnum *)COMPLETE_OAUTH {
  return ACAuthStateEnum_COMPLETE_OAUTH;
}

+ (ACAuthStateEnum *)SIGN_UP {
  return ACAuthStateEnum_SIGN_UP;
}

+ (ACAuthStateEnum *)LOGGED_IN {
  return ACAuthStateEnum_LOGGED_IN;
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  ACAuthStateEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *ACAuthStateEnum_values() {
  ACAuthStateEnum_initialize();
  return [IOSObjectArray arrayWithObjects:ACAuthStateEnum_values_ count:9 type:ACAuthStateEnum_class_()];
}

+ (IOSObjectArray *)values {
  return ACAuthStateEnum_values();
}

+ (ACAuthStateEnum *)valueOfWithNSString:(NSString *)name {
  return ACAuthStateEnum_valueOfWithNSString_(name);
}

ACAuthStateEnum *ACAuthStateEnum_valueOfWithNSString_(NSString *name) {
  ACAuthStateEnum_initialize();
  for (int i = 0; i < 9; i++) {
    ACAuthStateEnum *e = ACAuthStateEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

+ (void)initialize {
  if (self == [ACAuthStateEnum class]) {
    ACAuthStateEnum_AUTH_START = new_ACAuthStateEnum_initWithNSString_withInt_(@"AUTH_START", 0);
    ACAuthStateEnum_AUTH_EMAIL = new_ACAuthStateEnum_initWithNSString_withInt_(@"AUTH_EMAIL", 1);
    ACAuthStateEnum_AUTH_PHONE = new_ACAuthStateEnum_initWithNSString_withInt_(@"AUTH_PHONE", 2);
    ACAuthStateEnum_CODE_VALIDATION_PHONE = new_ACAuthStateEnum_initWithNSString_withInt_(@"CODE_VALIDATION_PHONE", 3);
    ACAuthStateEnum_CODE_VALIDATION_EMAIL = new_ACAuthStateEnum_initWithNSString_withInt_(@"CODE_VALIDATION_EMAIL", 4);
    ACAuthStateEnum_GET_OAUTH_PARAMS = new_ACAuthStateEnum_initWithNSString_withInt_(@"GET_OAUTH_PARAMS", 5);
    ACAuthStateEnum_COMPLETE_OAUTH = new_ACAuthStateEnum_initWithNSString_withInt_(@"COMPLETE_OAUTH", 6);
    ACAuthStateEnum_SIGN_UP = new_ACAuthStateEnum_initWithNSString_withInt_(@"SIGN_UP", 7);
    ACAuthStateEnum_LOGGED_IN = new_ACAuthStateEnum_initWithNSString_withInt_(@"LOGGED_IN", 8);
    J2OBJC_SET_INITIALIZED(ACAuthStateEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcFieldInfo fields[] = {
    { "AUTH_START", "AUTH_START", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_AUTH_START, NULL, .constantValue.asLong = 0 },
    { "AUTH_EMAIL", "AUTH_EMAIL", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_AUTH_EMAIL, NULL, .constantValue.asLong = 0 },
    { "AUTH_PHONE", "AUTH_PHONE", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_AUTH_PHONE, NULL, .constantValue.asLong = 0 },
    { "CODE_VALIDATION_PHONE", "CODE_VALIDATION_PHONE", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_CODE_VALIDATION_PHONE, NULL, .constantValue.asLong = 0 },
    { "CODE_VALIDATION_EMAIL", "CODE_VALIDATION_EMAIL", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_CODE_VALIDATION_EMAIL, NULL, .constantValue.asLong = 0 },
    { "GET_OAUTH_PARAMS", "GET_OAUTH_PARAMS", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_GET_OAUTH_PARAMS, NULL, .constantValue.asLong = 0 },
    { "COMPLETE_OAUTH", "COMPLETE_OAUTH", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_COMPLETE_OAUTH, NULL, .constantValue.asLong = 0 },
    { "SIGN_UP", "SIGN_UP", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_SIGN_UP, NULL, .constantValue.asLong = 0 },
    { "LOGGED_IN", "LOGGED_IN", 0x4019, "Lim.actor.core.AuthState;", &ACAuthStateEnum_LOGGED_IN, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Lim.actor.core.AuthState;"};
  static const J2ObjcClassInfo _ACAuthStateEnum = { 2, "AuthState", "im.actor.core", NULL, 0x4011, 0, NULL, 9, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Lim/actor/core/AuthState;>;" };
  return &_ACAuthStateEnum;
}

@end

void ACAuthStateEnum_initWithNSString_withInt_(ACAuthStateEnum *self, NSString *__name, jint __ordinal) {
  (void) JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

ACAuthStateEnum *new_ACAuthStateEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  ACAuthStateEnum *self = [ACAuthStateEnum alloc];
  ACAuthStateEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ACAuthStateEnum)

#pragma clang diagnostic pop
