//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-cocoa/src/main/java//im/actor/core/CocoaMessenger.java
//

#ifndef _ImActorCoreCocoaMessenger_H_
#define _ImActorCoreCocoaMessenger_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/core/Messenger.h"

@class ACConfiguration;
@class ACPeer;
@class ARBindedDisplayList;

@interface ACCocoaMessenger : ACMessenger

#pragma mark Public

/*!
 @brief Construct messenger
 @param configuration configuration of messenger
 */
- (instancetype)initWithConfiguration:(ACConfiguration *)configuration;

- (ARBindedDisplayList *)buildContactsDisplayList;

- (ARBindedDisplayList *)buildSearchDisplayList;

- (ARBindedDisplayList *)getDialogsDisplayList;

- (ARBindedDisplayList *)getMessageDisplayList:(ACPeer *)peer;

@end

J2OBJC_EMPTY_STATIC_INIT(ACCocoaMessenger)

FOUNDATION_EXPORT void ACCocoaMessenger_initWithConfiguration_(ACCocoaMessenger *self, ACConfiguration *configuration);

FOUNDATION_EXPORT ACCocoaMessenger *new_ACCocoaMessenger_initWithConfiguration_(ACConfiguration *configuration) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACCocoaMessenger)

@compatibility_alias ImActorCoreCocoaMessenger ACCocoaMessenger;


#pragma clang diagnostic pop
#endif // _ImActorCoreCocoaMessenger_H_
