//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/Messenger.java
//

#include "IOSClass.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/google/j2objc/annotations/ObjectiveCName.h"
#include "im/actor/core/AuthState.h"
#include "im/actor/core/Configuration.h"
#include "im/actor/core/Messenger.h"
#include "im/actor/core/api/ApiSex.h"
#include "im/actor/core/entity/FileReference.h"
#include "im/actor/core/entity/Peer.h"
#include "im/actor/core/entity/Sex.h"
#include "im/actor/core/entity/content/FastThumb.h"
#include "im/actor/core/i18n/I18nEngine.h"
#include "im/actor/core/modules/Authentication.h"
#include "im/actor/core/modules/ModuleContext.h"
#include "im/actor/core/modules/Modules.h"
#include "im/actor/core/modules/Updates.h"
#include "im/actor/core/modules/events/AppVisibleChanged.h"
#include "im/actor/core/modules/events/DialogsClosed.h"
#include "im/actor/core/modules/events/DialogsOpened.h"
#include "im/actor/core/modules/events/PeerChatClosed.h"
#include "im/actor/core/modules/events/PeerChatOpened.h"
#include "im/actor/core/modules/events/PeerInfoClosed.h"
#include "im/actor/core/modules/events/PeerInfoOpened.h"
#include "im/actor/core/modules/events/UserVisible.h"
#include "im/actor/core/modules/internal/AppStateModule.h"
#include "im/actor/core/modules/internal/ContactsModule.h"
#include "im/actor/core/modules/internal/ExternalModule.h"
#include "im/actor/core/modules/internal/FilesModule.h"
#include "im/actor/core/modules/internal/GroupsModule.h"
#include "im/actor/core/modules/internal/MentionsModule.h"
#include "im/actor/core/modules/internal/MessagesModule.h"
#include "im/actor/core/modules/internal/ProfileModule.h"
#include "im/actor/core/modules/internal/PushesModule.h"
#include "im/actor/core/modules/internal/SecurityModule.h"
#include "im/actor/core/modules/internal/SettingsModule.h"
#include "im/actor/core/modules/internal/TypingModule.h"
#include "im/actor/core/modules/internal/UsersModule.h"
#include "im/actor/core/network/ActorApi.h"
#include "im/actor/core/network/NetworkState.h"
#include "im/actor/core/util/ActorTrace.h"
#include "im/actor/core/util/Timing.h"
#include "im/actor/core/viewmodel/AppStateVM.h"
#include "im/actor/core/viewmodel/Command.h"
#include "im/actor/core/viewmodel/DialogGroupsVM.h"
#include "im/actor/core/viewmodel/FileCallback.h"
#include "im/actor/core/viewmodel/FileVM.h"
#include "im/actor/core/viewmodel/FileVMCallback.h"
#include "im/actor/core/viewmodel/GroupAvatarVM.h"
#include "im/actor/core/viewmodel/GroupTypingVM.h"
#include "im/actor/core/viewmodel/GroupVM.h"
#include "im/actor/core/viewmodel/OwnAvatarVM.h"
#include "im/actor/core/viewmodel/UploadFileCallback.h"
#include "im/actor/core/viewmodel/UploadFileVM.h"
#include "im/actor/core/viewmodel/UploadFileVMCallback.h"
#include "im/actor/core/viewmodel/UserTypingVM.h"
#include "im/actor/core/viewmodel/UserVM.h"
#include "im/actor/runtime/actors/ActorSystem.h"
#include "im/actor/runtime/eventbus/EventBus.h"
#include "im/actor/runtime/mvvm/MVVMCollection.h"
#include "im/actor/runtime/mvvm/ValueModel.h"
#include "im/actor/runtime/storage/PreferencesStorage.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/Messenger.java"


#line 64
@implementation ACMessenger


#line 74
- (instancetype)initWithConfiguration:(ACConfiguration *)configuration {
  ACMessenger_initWithConfiguration_(self, configuration);
  return self;
}


#line 104
- (ACAuthStateEnum *)getAuthState {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) getAuthState];
}


#line 113
- (jboolean)isLoggedIn {
  return [self getAuthState] == JreLoadStatic(ACAuthStateEnum, LOGGED_IN);
}


#line 125
- (id<ACCommand>)requestStartAuthCommandWithEmail:(NSString *)email {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) requestStartEmailAuthWithNSString:email];
}


#line 137
- (id<ACCommand>)requestStartAuthCommandWithPhone:(jlong)phone {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) requestStartPhoneAuthWithLong:phone];
}


#line 148
- (id<ACCommand>)requestGetOAuthParamsCommand {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) requestGetOAuth2Params];
}


#line 160
- (id<ACCommand>)requestCompleteOAuthCommandWithCode:(NSString *)code {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) requestCompleteOauthWithNSString:code];
}


#line 171
- (id<ACCommand>)requestPhoneCall {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) requestCallActivation];
}


#line 183
- (id<ACCommand>)validateCodeCommand:(NSString *)code {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) requestValidateCodeWithNSString:code];
}


#line 197
- (id<ACCommand>)signUpCommandWithName:(NSString *)name
                               WithSex:(ACSexEnum *)sex
                            withAvatar:(NSString *)avatarPath {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) signUpWithNSString:name withARApiSexEnum:JreLoadStatic(ARApiSexEnum, UNKNOWN) withNSString:avatarPath];
}


#line 208
- (jlong)getAuthPhone {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) getPhone];
}


#line 219
- (NSString *)getAuthEmail {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) getEmail];
}


#line 227
- (void)resetAuth {
  [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) resetAuth];
}

- (void)onLoggedIn {
}


#line 246
- (ACAppStateVM *)getAppState {
  return [((ACAppStateModule *) nil_chk([((ACModules *) nil_chk(modules_)) getAppStateModule])) getAppStateVM];
}


#line 256
- (jint)myUid {
  return [((ACAuthentication *) nil_chk([((ACModules *) nil_chk(modules_)) getAuthModule])) myUid];
}


#line 272
- (ARMVVMCollection *)getUsers {
  if ([((ACModules *) nil_chk(modules_)) getUsersModule] == nil) {
    return nil;
  }
  return [((ACUsersModule *) nil_chk([modules_ getUsersModule])) getUsers];
}


#line 287
- (ACUserVM *)getUserWithUid:(jint)uid {
  
#line 289
  return [((ARMVVMCollection *) nil_chk([self getUsers])) getWithId:uid];
}


#line 299
- (ARMVVMCollection *)getGroups {
  if ([((ACModules *) nil_chk(modules_)) getGroupsModule] == nil) {
    return nil;
  }
  return [((ACGroupsModule *) nil_chk([modules_ getGroupsModule])) getGroupsCollection];
}


#line 314
- (ACGroupVM *)getGroupWithGid:(jint)gid {
  
#line 316
  return [((ARMVVMCollection *) nil_chk([self getGroups])) getWithId:gid];
}


#line 326
- (ACDialogGroupsVM *)getDialogGroupsVM {
  return [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) getDialogGroupsVM];
}


#line 338
- (ARValueModel *)getTypingWithUid:(jint)uid {
  if ([((ACModules *) nil_chk(modules_)) getTypingModule] == nil) {
    return nil;
  }
  return [((ACUserTypingVM *) nil_chk([((ACTypingModule *) nil_chk([modules_ getTypingModule])) getTypingWithInt:uid])) getTyping];
}


#line 353
- (ARValueModel *)getGroupTypingWithGid:(jint)gid {
  if ([((ACModules *) nil_chk(modules_)) getTypingModule] == nil) {
    return nil;
  }
  return [((ACGroupTypingVM *) nil_chk([((ACTypingModule *) nil_chk([modules_ getTypingModule])) getGroupTypingWithInt:gid])) getActive];
}


#line 368
- (ACOwnAvatarVM *)getOwnAvatarVM {
  return [((ACProfileModule *) nil_chk([((ACModules *) nil_chk(modules_)) getProfileModule])) getOwnAvatarVM];
}


#line 381
- (ACGroupAvatarVM *)getGroupAvatarVMWithGid:(jint)gid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) getAvatarVMWithInt:gid];
}


#line 393
- (void)onAppVisible {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postStickyWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsAppVisibleChanged_initWithBoolean_(true)];
}


#line 401
- (void)onAppHidden {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postStickyWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsAppVisibleChanged_initWithBoolean_(false)];
}


#line 409
- (void)onDialogsOpen {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsDialogsOpened_init()];
}


#line 417
- (void)onDialogsClosed {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsDialogsClosed_init()];
}


#line 427
- (void)onConversationOpenWithPeer:(ACPeer *)peer {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsPeerChatOpened_initWithACPeer_(peer)];
}


#line 437
- (void)onConversationClosedWithPeer:(ACPeer *)peer {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsPeerChatClosed_initWithACPeer_(peer)];
}


#line 447
- (void)onProfileOpenWithUid:(jint)uid {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsPeerInfoOpened_initWithACPeer_(ACPeer_userWithInt_(uid))];
}


#line 457
- (void)onUserVisibleWithUid:(jint)uid {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsUserVisible_initWithInt_(uid)];
}


#line 467
- (void)onProfileClosedWithUid:(jint)uid {
  [((ImActorRuntimeEventbusEventBus *) nil_chk([((ACModules *) nil_chk(modules_)) getEvents])) postWithImActorRuntimeEventbusEvent:new_ImActorCoreModulesEventsPeerInfoClosed_initWithACPeer_(ACPeer_userWithInt_(uid))];
}


#line 478
- (void)onTypingWithPeer:(ACPeer *)peer {
  [((ACTypingModule *) nil_chk([((ACModules *) nil_chk(modules_)) getTypingModule])) onTypingWithACPeer:peer];
}


#line 491
- (void)onPhoneBookChanged {
  if ([((ACModules *) nil_chk(modules_)) getContactsModule] != nil) {
    [((ACContactsModule *) nil_chk([modules_ getContactsModule])) onPhoneBookChanged];
  }
}


#line 503
- (void)onNetworkChangedWithACNetworkStateEnum:(ACNetworkStateEnum *)state {
  [((ACActorApi *) nil_chk([((ACModules *) nil_chk(modules_)) getActorApi])) onNetworkChangedWithACNetworkStateEnum:state];
}


#line 513
- (void)onPushReceivedWithSeq:(jint)seq {
  if ([((ACModules *) nil_chk(modules_)) getUpdatesModule] != nil) {
    [((ACUpdates *) nil_chk([modules_ getUpdatesModule])) onPushReceivedWithInt:seq];
  }
}


#line 532
- (void)sendMessageWithPeer:(ACPeer *)peer
                   withText:(NSString *)text
           withMarkdownText:(NSString *)markDownText
               withMentions:(JavaUtilArrayList *)mentions
                 autoDetect:(jboolean)autoDetect {
  
#line 534
  [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) sendMessageWithACPeer:peer withNSString:text withNSString:markDownText withJavaUtilArrayList:mentions withBoolean:autoDetect];
}


#line 546
- (void)sendMessageWithPeer:(ACPeer *)peer
                   withText:(NSString *)text
           withMarkdownText:(NSString *)markDownText
               withMentions:(JavaUtilArrayList *)mentions {
  
#line 548
  [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) sendMessageWithACPeer:peer withNSString:text withNSString:markDownText withJavaUtilArrayList:mentions withBoolean:false];
}


#line 559
- (void)sendMessageWithPeer:(ACPeer *)peer
                   withText:(NSString *)text
           withMarkdownText:(NSString *)markDownText {
  [self sendMessageWithPeer:peer withText:text withMarkdownText:markDownText withMentions:nil autoDetect:false];
}


#line 571
- (void)sendMessageWithPeer:(ACPeer *)peer
                   withText:(NSString *)text
               withMentions:(JavaUtilArrayList *)mentions {
  [self sendMessageWithPeer:peer withText:text withMarkdownText:nil withMentions:mentions autoDetect:false];
}


#line 582
- (void)sendMessageWithPeer:(ACPeer *)peer
                   withText:(NSString *)text {
  [self sendMessageWithPeer:peer withText:text withMarkdownText:nil withMentions:nil autoDetect:false];
}


#line 593
- (void)sendMessageWithMentionsDetect:(ACPeer *)peer
                             withText:(NSString *)text {
  [self sendMessageWithPeer:peer withText:text withMarkdownText:nil withMentions:nil autoDetect:true];
}


#line 604
- (void)sendMessageWithMentionsDetect:(ACPeer *)peer
                             withText:(NSString *)text
                     withMarkdownText:(NSString *)markdownText {
  [self sendMessageWithPeer:peer withText:text withMarkdownText:markdownText withMentions:nil autoDetect:true];
}


#line 619
- (void)sendPhotoWithPeer:(ACPeer *)peer
                 withName:(NSString *)fileName
                    withW:(jint)w
                    withH:(jint)h
                withThumb:(ACFastThumb *)fastThumb
           withDescriptor:(NSString *)descriptor {
  
#line 622
  [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) sendPhotoWithACPeer:peer withNSString:fileName withInt:w withInt:h withACFastThumb:fastThumb withNSString:descriptor];
}


#line 637
- (void)sendVideoWithPeer:(ACPeer *)peer
                 withName:(NSString *)fileName
                    withW:(jint)w
                    withH:(jint)h
             withDuration:(jint)duration
                withThumb:(ACFastThumb *)fastThumb
           withDescriptor:(NSString *)descriptor {
  
#line 639
  [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) sendVideoWithACPeer:peer withNSString:fileName withInt:w withInt:h withInt:duration withACFastThumb:fastThumb withNSString:descriptor];
}


#line 651
- (void)sendDocumentWithPeer:(ACPeer *)peer
                    withName:(NSString *)fileName
                    withMime:(NSString *)mimeType
              withDescriptor:(NSString *)descriptor {
  [self sendDocumentWithPeer:peer withName:fileName withMime:mimeType withThumb:nil withDescriptor:descriptor];
}


#line 665
- (void)sendDocumentWithPeer:(ACPeer *)peer
                    withName:(NSString *)fileName
                    withMime:(NSString *)mimeType
                   withThumb:(ACFastThumb *)fastThumb
              withDescriptor:(NSString *)descriptor {
  
#line 667
  [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) sendDocumentWithACPeer:peer withNSString:fileName withNSString:mimeType withACFastThumb:fastThumb withNSString:descriptor];
}


#line 677
- (void)deleteMessagesWithPeer:(ACPeer *)peer
                      withRids:(IOSLongArray *)rids {
  [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) deleteMessagesWithACPeer:peer withLongArray:rids];
}


#line 688
- (id<ACCommand>)deleteChatCommandWithPeer:(ACPeer *)peer {
  return [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) deleteChatWithACPeer:peer];
}


#line 699
- (id<ACCommand>)clearChatCommandWithPeer:(ACPeer *)peer {
  return [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) clearChatWithACPeer:peer];
}


#line 710
- (void)saveDraftWithPeer:(ACPeer *)peer
                withDraft:(NSString *)draft {
  [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) saveDraftWithACPeer:peer withNSString:draft];
}


#line 722
- (NSString *)loadDraftWithPeer:(ACPeer *)peer {
  return [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) loadDraftWithACPeer:peer];
}


#line 733
- (jlong)loadFirstUnread:(ACPeer *)peer {
  return [((ACMessagesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMessagesModule])) loadReadStateWithACPeer:peer];
}


#line 745
- (id<JavaUtilList>)findMentionsWithGid:(jint)gid
                              withQuery:(NSString *)query {
  return [((ACMentionsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getMentions])) findMentionsWithInt:gid withNSString:query];
}


#line 761
- (id<ACCommand>)editMyNameCommandWithName:(NSString *)newName {
  return [((ACUsersModule *) nil_chk([((ACModules *) nil_chk(modules_)) getUsersModule])) editMyNameWithNSString:newName];
}


#line 773
- (id<ACCommand>)editMyNickCommandWithNick:(NSString *)newNick {
  return [((ACUsersModule *) nil_chk([((ACModules *) nil_chk(modules_)) getUsersModule])) editNickWithNSString:newNick];
}


#line 785
- (id<ACCommand>)editMyAboutCommandWithNick:(NSString *)newAbout {
  return [((ACUsersModule *) nil_chk([((ACModules *) nil_chk(modules_)) getUsersModule])) editAboutWithNSString:newAbout];
}


#line 795
- (void)changeMyAvatarWithDescriptor:(NSString *)descriptor {
  [((ACProfileModule *) nil_chk([((ACModules *) nil_chk(modules_)) getProfileModule])) changeAvatarWithNSString:descriptor];
}


#line 803
- (void)removeMyAvatar {
  [((ACProfileModule *) nil_chk([((ACModules *) nil_chk(modules_)) getProfileModule])) removeAvatar];
}


#line 816
- (id<ACCommand>)editNameCommandWithUid:(jint)uid
                               withName:(NSString *)name {
  return [((ACUsersModule *) nil_chk([((ACModules *) nil_chk(modules_)) getUsersModule])) editNameWithInt:uid withNSString:name];
}


#line 829
- (id<ACCommand>)editGroupTitleCommandWithGid:(jint)gid
                                    withTitle:(NSString *)title {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) editTitleWithInt:gid withNSString:title];
}


#line 842
- (id<ACCommand>)editGroupThemeCommandWithGid:(jint)gid
                                    withTheme:(NSString *)theme {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) editThemeWithInt:gid withNSString:theme];
}


#line 855
- (id<ACCommand>)editGroupAboutCommandWithGid:(jint)gid
                                    withAbout:(NSString *)about {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) editAboutWithInt:gid withNSString:about];
}


#line 866
- (void)changeGroupAvatarWithGid:(jint)gid
                  withDescriptor:(NSString *)descriptor {
  [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) changeAvatarWithInt:gid withNSString:descriptor];
}


#line 876
- (void)removeGroupAvatarWithGid:(jint)gid {
  [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) removeAvatarWithInt:gid];
}


#line 895
- (id<ACCommand>)createGroupCommandWithTitle:(NSString *)title
                                  withAvatar:(NSString *)avatarDescriptor
                                    withUids:(IOSIntArray *)uids {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) createGroupWithNSString:title withNSString:avatarDescriptor withIntArray:uids];
}


#line 908
- (id<ACCommand>)leaveGroupCommandWithGid:(jint)gid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) leaveGroupWithInt:gid];
}


#line 921
- (id<ACCommand>)inviteMemberCommandWithGid:(jint)gid
                                    withUid:(jint)uid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) addMemberToGroupWithInt:gid withInt:uid];
}


#line 934
- (id<ACCommand>)kickMemberCommandWithGid:(jint)gid
                                  withUid:(jint)uid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) kickMemberWithInt:gid withInt:uid];
}


#line 947
- (id<ACCommand>)makeAdminCommandWithGid:(jint)gid
                                 withUid:(jint)uid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) makeAdminWithInt:gid withInt:uid];
}


#line 959
- (id<ACCommand>)requestInviteLinkCommandWithGid:(jint)gid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) requestInviteLinkWithInt:gid];
}


#line 971
- (id<ACCommand>)requestRevokeLinkCommandWithGid:(jint)gid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) requestRevokeLinkWithInt:gid];
}


#line 983
- (id<ACCommand>)joinGroupViaLinkCommandWithUrl:(NSString *)url {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) joinGroupViaLinkWithNSString:url];
}


#line 996
- (id<ACCommand>)joinPublicGroupCommandWithGig:(jint)gid
                                withAccessHash:(jlong)accessHash {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) joinPublicGroupWithInt:gid withLong:accessHash];
}


#line 1007
- (id<ACCommand>)listPublicGroups {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) listPublicGroups];
}


#line 1020
- (id<ACCommand>)requestIntegrationTokenCommandWithGid:(jint)gid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) requestIntegrationTokenWithInt:gid];
}


#line 1032
- (id<ACCommand>)revokeIntegrationTokenCommandWithGid:(jint)gid {
  return [((ACGroupsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getGroupsModule])) revokeIntegrationTokenWithInt:gid];
}


#line 1048
- (id<ACCommand>)removeContactCommandWithUid:(jint)uid {
  return [((ACContactsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getContactsModule])) removeContactWithInt:uid];
}


#line 1060
- (id<ACCommand>)addContactCommandWithUid:(jint)uid {
  return [((ACContactsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getContactsModule])) addContactWithInt:uid];
}


#line 1072
- (id<ACCommand>)findUsersCommandWithQuery:(NSString *)query {
  return [((ACContactsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getContactsModule])) findUsersWithNSString:query];
}


#line 1087
- (ACFileVM *)bindFileWithReference:(ACFileReference *)fileReference
                          autoStart:(jboolean)isAutoStart
                       withCallback:(id<ACFileVMCallback>)callback {
  return new_ACFileVM_initWithACFileReference_withBoolean_withACModules_withACFileVMCallback_(fileReference, isAutoStart, modules_, callback);
}


#line 1100
- (ACUploadFileVM *)bindUploadWithRid:(jlong)rid
                         withCallback:(id<ACUploadFileVMCallback>)callback {
  return new_ACUploadFileVM_initWithLong_withACUploadFileVMCallback_withACModules_(rid, callback, modules_);
}


#line 1112
- (void)bindRawFileWithReference:(ACFileReference *)fileReference
                       autoStart:(jboolean)isAutoStart
                    withCallback:(id<ACFileCallback>)callback {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) bindFileWithACFileReference:fileReference withBoolean:isAutoStart withACFileCallback:callback];
}


#line 1124
- (void)unbindRawFileWithFileId:(jlong)fileId
                     autoCancel:(jboolean)isAutoCancel
                   withCallback:(id<ACFileCallback>)callback {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) unbindFileWithLong:fileId withACFileCallback:callback withBoolean:isAutoCancel];
}


#line 1135
- (void)bindRawUploadFileWithRid:(jlong)rid
                    withCallback:(id<ACUploadFileCallback>)callback {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) bindUploadFileWithLong:rid withACUploadFileCallback:callback];
}


#line 1146
- (void)unbindRawUploadFileWithRid:(jlong)rid
                      withCallback:(id<ACUploadFileCallback>)callback {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) unbindUploadFileWithLong:rid withACUploadFileCallback:callback];
}


#line 1157
- (void)requestStateWithFileId:(jlong)fileId
                  withCallback:(id<ACFileCallback>)callback {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) requestStateWithLong:fileId withACFileCallback:callback];
}


#line 1168
- (void)requestUploadStateWithRid:(jlong)rid
                     withCallback:(id<ACUploadFileCallback>)callback {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) requestUploadStateWithLong:rid withACUploadFileCallback:callback];
}


#line 1178
- (void)cancelDownloadingWithFileId:(jlong)fileId {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) cancelDownloadingWithLong:fileId];
}


#line 1188
- (void)startDownloadingWithReference:(ACFileReference *)reference {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) startDownloadingWithACFileReference:reference];
}


#line 1198
- (void)resumeUploadWithRid:(jlong)rid {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) resumeUploadWithLong:rid];
}


#line 1208
- (void)pauseUploadWithRid:(jlong)rid {
  [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) pauseUploadWithLong:rid];
}


#line 1220
- (NSString *)findDownloadedDescriptorWithFileId:(jlong)fileId {
  return [((ACFilesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getFilesModule])) getDownloadedDescriptorWithLong:fileId];
}


#line 1234
- (jboolean)isConversationTonesEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isConversationTonesEnabled];
}


#line 1244
- (void)changeConversationTonesEnabledWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeConversationTonesEnabledWithBoolean:val];
}


#line 1254
- (jboolean)isNotificationsEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isNotificationsEnabled];
}


#line 1264
- (void)changeNotificationsEnabledWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeNotificationsEnabledWithBoolean:val];
}


#line 1274
- (jboolean)isNotificationSoundEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isNotificationSoundEnabled];
}


#line 1284
- (void)changeNotificationSoundEnabledWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeNotificationSoundEnabledWithBoolean:val];
}


#line 1295
- (NSString *)getNotificationSound {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) getNotificationSound];
}


#line 1305
- (void)changeNotificationSoundWithSound:(NSString *)sound {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeNotificationSoundWithNSString:sound];
}


#line 1315
- (jboolean)isNotificationVibrationEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isVibrationEnabled];
}


#line 1325
- (void)changeNotificationVibrationEnabledWithValueWithBoolean:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeNotificationVibrationEnabledWithBoolean:val];
}


#line 1335
- (jboolean)isShowNotificationsText {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isShowNotificationsText];
}


#line 1345
- (void)changeShowNotificationTextEnabledWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeShowNotificationTextEnabledWithBoolean:val];
}


#line 1355
- (jboolean)isSendByEnterEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isSendByEnterEnabled];
}


#line 1365
- (void)changeSendByEnterWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeSendByEnterWithBoolean:val];
}


#line 1375
- (jboolean)isMarkdownEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isMarkdownEnabled];
}


#line 1385
- (void)changeMarkdownWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeMarkdownWithBoolean:val];
}


#line 1396
- (jboolean)isNotificationsEnabledWithPeer:(ACPeer *)peer {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isNotificationsEnabledWithACPeer:peer];
}


#line 1407
- (void)changeNotificationsEnabledWithPeer:(ACPeer *)peer
                                 withValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeNotificationsEnabledWithACPeer:peer withBoolean:val];
}


#line 1417
- (jboolean)isInAppNotificationsEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isInAppEnabled];
}


#line 1427
- (void)changeInAppNotificationsEnabledWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeInAppEnabledWithBoolean:val];
}


#line 1437
- (jboolean)isInAppNotificationSoundEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isInAppSoundEnabled];
}


#line 1447
- (void)changeInAppNotificationSoundEnabledWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeInAppSoundEnabledWithBoolean:val];
}


#line 1457
- (jboolean)isInAppNotificationVibrationEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isInAppVibrationEnabled];
}


#line 1467
- (void)changeInAppNotificationVibrationEnabledWithValue:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeInAppVibrationEnabledWithBoolean:val];
}


#line 1477
- (jboolean)isGroupNotificationsEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isGroupNotificationsEnabled];
}


#line 1487
- (void)changeGroupNotificationsEnabled:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeGroupNotificationsEnabledWithBoolean:val];
}


#line 1497
- (jboolean)isGroupNotificationsOnlyMentionsEnabled {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isGroupNotificationsOnlyMentionsEnabled];
}


#line 1507
- (void)changeGroupNotificationsOnlyMentionsEnabled:(jboolean)val {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeGroupNotificationsOnlyMentionsEnabledWithBoolean:val];
}


#line 1517
- (jboolean)isRenameHintShown {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) isRenameHintShown];
}


#line 1527
- (NSString *)getSelectedWallpaper {
  return [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) getSelectedWallpapper];
}


#line 1537
- (void)changeSelectedWallpaper:(NSString *)uri {
  [((ACSettingsModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSettingsModule])) changeSelectedWallpapperWithNSString:uri];
}


#line 1552
- (id<ACCommand>)loadSessionsCommand {
  return [((ACSecurityModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSecurityModule])) loadSessions];
}


#line 1563
- (id<ACCommand>)terminateAllSessionsCommand {
  return [((ACSecurityModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSecurityModule])) terminateAllSessions];
}


#line 1575
- (id<ACCommand>)terminateSessionCommandWithId:(jint)id_ {
  return [((ACSecurityModule *) nil_chk([((ACModules *) nil_chk(modules_)) getSecurityModule])) terminateSessionWithInt:id_];
}


#line 1590
- (id<ACCommand>)startWebAction:(NSString *)webAction {
  return [((ACExternalModule *) nil_chk([((ACModules *) nil_chk(modules_)) getExternalModule])) startWebActionWithNSString:webAction];
}


#line 1602
- (id<ACCommand>)completeWebActionWithHash:(NSString *)actionHash
                                   withUrl:(NSString *)url {
  return [((ACExternalModule *) nil_chk([((ACModules *) nil_chk(modules_)) getExternalModule])) completeWebActionWithNSString:actionHash withNSString:url];
}


#line 1617
- (ACI18nEngine *)getFormatter {
  return [((ACModules *) nil_chk(modules_)) getI18nModule];
}


#line 1628
- (void)registerGooglePushWithProjectId:(jlong)projectId
                              withToken:(NSString *)token {
  [((ACPushesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getPushesModule])) registerGooglePushWithLong:projectId withNSString:token];
}


#line 1639
- (void)registerApplePushWithApnsId:(jint)apnsId
                          withToken:(NSString *)token {
  [((ACPushesModule *) nil_chk([((ACModules *) nil_chk(modules_)) getPushesModule])) registerApplePushWithInt:apnsId withNSString:token];
}


#line 1650
- (id<ARPreferencesStorage>)getPreferences {
  return [((ACModules *) nil_chk(modules_)) getPreferences];
}


#line 1658
- (void)forceNetworkCheck {
  [((ACActorApi *) nil_chk([((ACModules *) nil_chk(modules_)) getActorApi])) forceNetworkCheck];
}


#line 1667
- (id<ACModuleContext>)getModuleContext {
  return modules_;
}

+ (IOSObjectArray *)__annotations_initWithACConfiguration_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"initWithConfiguration:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestStartEmailAuthWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestStartAuthCommandWithEmail:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestStartPhoneAuthWithLong_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestStartAuthCommandWithPhone:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestGetOAuthParams {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestGetOAuthParamsCommand"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestCompleteOAuthWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestCompleteOAuthCommandWithCode:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestPhoneCall {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestPhoneCall"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_validateCodeWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"validateCodeCommand:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_signUpWithNSString_withACSexEnum_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"signUpCommandWithName:WithSex:withAvatar:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getAuthPhone {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getAuthPhone"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getAuthEmail {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getAuthEmail"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_resetAuth {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"resetAuth"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getAppState {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getAppState"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_myUid {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"myUid"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getUsers {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getUsers"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getUserWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getUserWithUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getGroups {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getGroups"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getGroupWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getGroupWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getDialogGroupsVM {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getDialogGroupsVM"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getTypingWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getTypingWithUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getGroupTypingWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getGroupTypingWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getOwnAvatarVM {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getOwnAvatarVM"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getGroupAvatarVMWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getGroupAvatarVMWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onAppVisible {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onAppVisible"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onAppHidden {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onAppHidden"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onDialogsOpen {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onDialogsOpen"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onDialogsClosed {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onDialogsClosed"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onConversationOpenWithACPeer_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onConversationOpenWithPeer:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onConversationClosedWithACPeer_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onConversationClosedWithPeer:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onProfileOpenWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onProfileOpenWithUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onUserVisibleWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onUserVisibleWithUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onProfileClosedWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onProfileClosedWithUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onTypingWithACPeer_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onTypingWithPeer:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onPhoneBookChanged {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onPhoneBookChanged"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onNetworkChangedWithACNetworkStateEnum_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onNetworkChanged"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_onPushReceivedWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"onPushReceivedWithSeq:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendMessageWithACPeer_withNSString_withNSString_withJavaUtilArrayList_withBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendMessageWithPeer:withText:withMarkdownText:withMentions:autoDetect:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendMessageWithACPeer_withNSString_withNSString_withJavaUtilArrayList_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendMessageWithPeer:withText:withMarkdownText:withMentions:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendMessageWithACPeer_withNSString_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendMessageWithPeer:withText:withMarkdownText:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendMessageWithACPeer_withNSString_withJavaUtilArrayList_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendMessageWithPeer:withText:withMentions:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendMessageWithACPeer_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendMessageWithPeer:withText:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendMessageWithMentionsDetectWithACPeer_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendMessageWithMentionsDetect:withText:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendMessageWithMentionsDetectWithACPeer_withNSString_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendMessageWithMentionsDetect:withText:withMarkdownText:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendPhotoWithACPeer_withNSString_withInt_withInt_withACFastThumb_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendPhotoWithPeer:withName:withW:withH:withThumb:withDescriptor:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendVideoWithACPeer_withNSString_withInt_withInt_withInt_withACFastThumb_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendVideoWithPeer:withName:withW:withH:withDuration:withThumb:withDescriptor:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendDocumentWithACPeer_withNSString_withNSString_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendDocumentWithPeer:withName:withMime:withDescriptor:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_sendDocumentWithACPeer_withNSString_withNSString_withACFastThumb_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"sendDocumentWithPeer:withName:withMime:withThumb:withDescriptor:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_deleteMessagesWithACPeer_withLongArray_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"deleteMessagesWithPeer:withRids:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_deleteChatWithACPeer_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"deleteChatCommandWithPeer:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_clearChatWithACPeer_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"clearChatCommandWithPeer:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_saveDraftWithACPeer_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"saveDraftWithPeer:withDraft:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_loadDraftWithACPeer_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"loadDraftWithPeer:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_loadFirstUnreadWithACPeer_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"loadFirstUnread:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_findMentionsWithInt_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"findMentionsWithGid:withQuery:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_editMyNameWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"editMyNameCommandWithName:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_editMyNickWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"editMyNickCommandWithNick:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_editMyAboutWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"editMyAboutCommandWithNick:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeMyAvatarWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeMyAvatarWithDescriptor:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_removeMyAvatar {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"removeMyAvatar"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_editNameWithInt_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"editNameCommandWithUid:withName:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_editGroupTitleWithInt_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"editGroupTitleCommandWithGid:withTitle:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_editGroupThemeWithInt_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"editGroupThemeCommandWithGid:withTheme:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_editGroupAboutWithInt_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"editGroupAboutCommandWithGid:withAbout:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeGroupAvatarWithInt_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeGroupAvatarWithGid:withDescriptor:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_removeGroupAvatarWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"removeGroupAvatarWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_createGroupWithNSString_withNSString_withIntArray_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"createGroupCommandWithTitle:withAvatar:withUids:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_leaveGroupWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"leaveGroupCommandWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_inviteMemberWithInt_withInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"inviteMemberCommandWithGid:withUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_kickMemberWithInt_withInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"kickMemberCommandWithGid:withUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_makeAdminWithInt_withInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"makeAdminCommandWithGid:withUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestInviteLinkWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestInviteLinkCommandWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_revokeInviteLinkWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestRevokeLinkCommandWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_joinGroupViaLinkWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"joinGroupViaLinkCommandWithUrl:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_joinPublicGroupWithInt_withLong_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"joinPublicGroupCommandWithGig:withAccessHash:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_listPublicGroups {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"listPublicGroups"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestIntegrationTokenWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestIntegrationTokenCommandWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_revokeIntegrationTokenWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"revokeIntegrationTokenCommandWithGid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_removeContactWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"removeContactCommandWithUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_addContactWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"addContactCommandWithUid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_findUsersWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"findUsersCommandWithQuery:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_bindFileWithACFileReference_withBoolean_withACFileVMCallback_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"bindFileWithReference:autoStart:withCallback:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_bindUploadWithLong_withACUploadFileVMCallback_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"bindUploadWithRid:withCallback:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_bindRawFileWithACFileReference_withBoolean_withACFileCallback_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"bindRawFileWithReference:autoStart:withCallback:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_unbindRawFileWithLong_withBoolean_withACFileCallback_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"unbindRawFileWithFileId:autoCancel:withCallback:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_bindRawUploadFileWithLong_withACUploadFileCallback_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"bindRawUploadFileWithRid:withCallback:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_unbindRawUploadFileWithLong_withACUploadFileCallback_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"unbindRawUploadFileWithRid:withCallback:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestStateWithLong_withACFileCallback_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestStateWithFileId:withCallback:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_requestUploadStateWithLong_withACUploadFileCallback_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"requestUploadStateWithRid:withCallback:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_cancelDownloadingWithLong_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"cancelDownloadingWithFileId:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_startDownloadingWithACFileReference_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"startDownloadingWithReference:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_resumeUploadWithLong_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"resumeUploadWithRid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_pauseUploadWithLong_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"pauseUploadWithRid:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_findDownloadedDescriptorWithLong_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"findDownloadedDescriptorWithFileId:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isConversationTonesEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isConversationTonesEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeConversationTonesEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeConversationTonesEnabledWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isNotificationsEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isNotificationsEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeNotificationsEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeNotificationsEnabledWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isNotificationSoundEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isNotificationSoundEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeNotificationSoundEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeNotificationSoundEnabledWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getNotificationSound {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getNotificationSound"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeNotificationSoundWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeNotificationSoundWithSound:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isNotificationVibrationEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isNotificationVibrationEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeNotificationVibrationEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeNotificationVibrationEnabledWithValue"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isShowNotificationsText {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isShowNotificationsText"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeShowNotificationTextEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeShowNotificationTextEnabledWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isSendByEnterEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isSendByEnterEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeSendByEnterWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeSendByEnterWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isMarkdownEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isMarkdownEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeMarkdownWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeMarkdownWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isNotificationsEnabledWithACPeer_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isNotificationsEnabledWithPeer:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeNotificationsEnabledWithACPeer_withBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeNotificationsEnabledWithPeer:withValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isInAppNotificationsEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isInAppNotificationsEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeInAppNotificationsEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeInAppNotificationsEnabledWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isInAppNotificationSoundEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isInAppNotificationSoundEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeInAppNotificationSoundEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeInAppNotificationSoundEnabledWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isInAppNotificationVibrationEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isInAppNotificationVibrationEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeInAppNotificationVibrationEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeInAppNotificationVibrationEnabledWithValue:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isGroupNotificationsEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isGroupNotificationsEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeGroupNotificationsEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeGroupNotificationsEnabled:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isGroupNotificationsOnlyMentionsEnabled {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isGroupNotificationsOnlyMentionsEnabled"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeGroupNotificationsOnlyMentionsEnabledWithBoolean_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeGroupNotificationsOnlyMentionsEnabled:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_isRenameHintShown {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"isRenameHintShown"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getSelectedWallpaper {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getSelectedWallpaper"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_changeSelectedWallpaperWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"changeSelectedWallpaper:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_loadSessions {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"loadSessionsCommand"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_terminateAllSessions {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"terminateAllSessionsCommand"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_terminateSessionWithInt_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"terminateSessionCommandWithId:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_startWebActionWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"startWebAction:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_completeWebActionWithNSString_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"completeWebActionWithHash:withUrl:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getFormatter {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getFormatter"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_registerGooglePushWithLong_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"registerGooglePushWithProjectId:withToken:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_registerApplePushWithInt_withNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"registerApplePushWithApnsId:withToken:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_getPreferences {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"getPreferences"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_forceNetworkCheck {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"forceNetworkCheck"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithConfiguration:", "Messenger", NULL, 0x1, NULL, NULL },
    { "getAuthState", NULL, "Lim.actor.core.AuthState;", 0x1, NULL, NULL },
    { "isLoggedIn", NULL, "Z", 0x1, NULL, NULL },
    { "requestStartAuthCommandWithEmail:", "requestStartEmailAuth", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "requestStartAuthCommandWithPhone:", "requestStartPhoneAuth", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "requestGetOAuthParamsCommand", "requestGetOAuthParams", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "requestCompleteOAuthCommandWithCode:", "requestCompleteOAuth", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "requestPhoneCall", NULL, "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "validateCodeCommand:", "validateCode", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "signUpCommandWithName:WithSex:withAvatar:", "signUp", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "getAuthPhone", NULL, "J", 0x1, NULL, NULL },
    { "getAuthEmail", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "resetAuth", NULL, "V", 0x1, NULL, NULL },
    { "onLoggedIn", NULL, "V", 0x1, NULL, NULL },
    { "getAppState", NULL, "Lim.actor.core.viewmodel.AppStateVM;", 0x1, NULL, NULL },
    { "myUid", NULL, "I", 0x1, NULL, NULL },
    { "getUsers", NULL, "Lim.actor.runtime.mvvm.MVVMCollection;", 0x1, NULL, NULL },
    { "getUserWithUid:", "getUser", "Lim.actor.core.viewmodel.UserVM;", 0x1, NULL, NULL },
    { "getGroups", NULL, "Lim.actor.runtime.mvvm.MVVMCollection;", 0x1, NULL, NULL },
    { "getGroupWithGid:", "getGroup", "Lim.actor.core.viewmodel.GroupVM;", 0x1, NULL, NULL },
    { "getDialogGroupsVM", NULL, "Lim.actor.core.viewmodel.DialogGroupsVM;", 0x1, NULL, NULL },
    { "getTypingWithUid:", "getTyping", "Lim.actor.runtime.mvvm.ValueModel;", 0x1, NULL, NULL },
    { "getGroupTypingWithGid:", "getGroupTyping", "Lim.actor.runtime.mvvm.ValueModel;", 0x1, NULL, NULL },
    { "getOwnAvatarVM", NULL, "Lim.actor.core.viewmodel.OwnAvatarVM;", 0x1, NULL, NULL },
    { "getGroupAvatarVMWithGid:", "getGroupAvatarVM", "Lim.actor.core.viewmodel.GroupAvatarVM;", 0x1, NULL, NULL },
    { "onAppVisible", NULL, "V", 0x1, NULL, NULL },
    { "onAppHidden", NULL, "V", 0x1, NULL, NULL },
    { "onDialogsOpen", NULL, "V", 0x1, NULL, NULL },
    { "onDialogsClosed", NULL, "V", 0x1, NULL, NULL },
    { "onConversationOpenWithPeer:", "onConversationOpen", "V", 0x1, NULL, NULL },
    { "onConversationClosedWithPeer:", "onConversationClosed", "V", 0x1, NULL, NULL },
    { "onProfileOpenWithUid:", "onProfileOpen", "V", 0x1, NULL, NULL },
    { "onUserVisibleWithUid:", "onUserVisible", "V", 0x1, NULL, NULL },
    { "onProfileClosedWithUid:", "onProfileClosed", "V", 0x1, NULL, NULL },
    { "onTypingWithPeer:", "onTyping", "V", 0x1, NULL, NULL },
    { "onPhoneBookChanged", NULL, "V", 0x1, NULL, NULL },
    { "onNetworkChangedWithACNetworkStateEnum:", "onNetworkChanged", "V", 0x1, NULL, NULL },
    { "onPushReceivedWithSeq:", "onPushReceived", "V", 0x1, NULL, NULL },
    { "sendMessageWithPeer:withText:withMarkdownText:withMentions:autoDetect:", "sendMessage", "V", 0x1, NULL, NULL },
    { "sendMessageWithPeer:withText:withMarkdownText:withMentions:", "sendMessage", "V", 0x1, NULL, NULL },
    { "sendMessageWithPeer:withText:withMarkdownText:", "sendMessage", "V", 0x1, NULL, NULL },
    { "sendMessageWithPeer:withText:withMentions:", "sendMessage", "V", 0x1, NULL, NULL },
    { "sendMessageWithPeer:withText:", "sendMessage", "V", 0x1, NULL, NULL },
    { "sendMessageWithMentionsDetect:withText:", "sendMessageWithMentionsDetect", "V", 0x1, NULL, NULL },
    { "sendMessageWithMentionsDetect:withText:withMarkdownText:", "sendMessageWithMentionsDetect", "V", 0x1, NULL, NULL },
    { "sendPhotoWithPeer:withName:withW:withH:withThumb:withDescriptor:", "sendPhoto", "V", 0x1, NULL, NULL },
    { "sendVideoWithPeer:withName:withW:withH:withDuration:withThumb:withDescriptor:", "sendVideo", "V", 0x1, NULL, NULL },
    { "sendDocumentWithPeer:withName:withMime:withDescriptor:", "sendDocument", "V", 0x1, NULL, NULL },
    { "sendDocumentWithPeer:withName:withMime:withThumb:withDescriptor:", "sendDocument", "V", 0x1, NULL, NULL },
    { "deleteMessagesWithPeer:withRids:", "deleteMessages", "V", 0x1, NULL, NULL },
    { "deleteChatCommandWithPeer:", "deleteChat", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "clearChatCommandWithPeer:", "clearChat", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "saveDraftWithPeer:withDraft:", "saveDraft", "V", 0x1, NULL, NULL },
    { "loadDraftWithPeer:", "loadDraft", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "loadFirstUnread:", "loadFirstUnread", "J", 0x1, NULL, NULL },
    { "findMentionsWithGid:withQuery:", "findMentions", "Ljava.util.List;", 0x1, NULL, NULL },
    { "editMyNameCommandWithName:", "editMyName", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "editMyNickCommandWithNick:", "editMyNick", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "editMyAboutCommandWithNick:", "editMyAbout", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "changeMyAvatarWithDescriptor:", "changeMyAvatar", "V", 0x1, NULL, NULL },
    { "removeMyAvatar", NULL, "V", 0x1, NULL, NULL },
    { "editNameCommandWithUid:withName:", "editName", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "editGroupTitleCommandWithGid:withTitle:", "editGroupTitle", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "editGroupThemeCommandWithGid:withTheme:", "editGroupTheme", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "editGroupAboutCommandWithGid:withAbout:", "editGroupAbout", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "changeGroupAvatarWithGid:withDescriptor:", "changeGroupAvatar", "V", 0x1, NULL, NULL },
    { "removeGroupAvatarWithGid:", "removeGroupAvatar", "V", 0x1, NULL, NULL },
    { "createGroupCommandWithTitle:withAvatar:withUids:", "createGroup", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "leaveGroupCommandWithGid:", "leaveGroup", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "inviteMemberCommandWithGid:withUid:", "inviteMember", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "kickMemberCommandWithGid:withUid:", "kickMember", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "makeAdminCommandWithGid:withUid:", "makeAdmin", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "requestInviteLinkCommandWithGid:", "requestInviteLink", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "requestRevokeLinkCommandWithGid:", "revokeInviteLink", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "joinGroupViaLinkCommandWithUrl:", "joinGroupViaLink", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "joinPublicGroupCommandWithGig:withAccessHash:", "joinPublicGroup", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "listPublicGroups", NULL, "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "requestIntegrationTokenCommandWithGid:", "requestIntegrationToken", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "revokeIntegrationTokenCommandWithGid:", "revokeIntegrationToken", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "removeContactCommandWithUid:", "removeContact", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "addContactCommandWithUid:", "addContact", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "findUsersCommandWithQuery:", "findUsers", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "bindFileWithReference:autoStart:withCallback:", "bindFile", "Lim.actor.core.viewmodel.FileVM;", 0x1, NULL, NULL },
    { "bindUploadWithRid:withCallback:", "bindUpload", "Lim.actor.core.viewmodel.UploadFileVM;", 0x1, NULL, NULL },
    { "bindRawFileWithReference:autoStart:withCallback:", "bindRawFile", "V", 0x1, NULL, NULL },
    { "unbindRawFileWithFileId:autoCancel:withCallback:", "unbindRawFile", "V", 0x1, NULL, NULL },
    { "bindRawUploadFileWithRid:withCallback:", "bindRawUploadFile", "V", 0x1, NULL, NULL },
    { "unbindRawUploadFileWithRid:withCallback:", "unbindRawUploadFile", "V", 0x1, NULL, NULL },
    { "requestStateWithFileId:withCallback:", "requestState", "V", 0x1, NULL, NULL },
    { "requestUploadStateWithRid:withCallback:", "requestUploadState", "V", 0x1, NULL, NULL },
    { "cancelDownloadingWithFileId:", "cancelDownloading", "V", 0x1, NULL, NULL },
    { "startDownloadingWithReference:", "startDownloading", "V", 0x1, NULL, NULL },
    { "resumeUploadWithRid:", "resumeUpload", "V", 0x1, NULL, NULL },
    { "pauseUploadWithRid:", "pauseUpload", "V", 0x1, NULL, NULL },
    { "findDownloadedDescriptorWithFileId:", "findDownloadedDescriptor", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "isConversationTonesEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeConversationTonesEnabledWithValue:", "changeConversationTonesEnabled", "V", 0x1, NULL, NULL },
    { "isNotificationsEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeNotificationsEnabledWithValue:", "changeNotificationsEnabled", "V", 0x1, NULL, NULL },
    { "isNotificationSoundEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeNotificationSoundEnabledWithValue:", "changeNotificationSoundEnabled", "V", 0x1, NULL, NULL },
    { "getNotificationSound", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "changeNotificationSoundWithSound:", "changeNotificationSound", "V", 0x1, NULL, NULL },
    { "isNotificationVibrationEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeNotificationVibrationEnabledWithValueWithBoolean:", "changeNotificationVibrationEnabled", "V", 0x1, NULL, NULL },
    { "isShowNotificationsText", NULL, "Z", 0x1, NULL, NULL },
    { "changeShowNotificationTextEnabledWithValue:", "changeShowNotificationTextEnabled", "V", 0x1, NULL, NULL },
    { "isSendByEnterEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeSendByEnterWithValue:", "changeSendByEnter", "V", 0x1, NULL, NULL },
    { "isMarkdownEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeMarkdownWithValue:", "changeMarkdown", "V", 0x1, NULL, NULL },
    { "isNotificationsEnabledWithPeer:", "isNotificationsEnabled", "Z", 0x1, NULL, NULL },
    { "changeNotificationsEnabledWithPeer:withValue:", "changeNotificationsEnabled", "V", 0x1, NULL, NULL },
    { "isInAppNotificationsEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeInAppNotificationsEnabledWithValue:", "changeInAppNotificationsEnabled", "V", 0x1, NULL, NULL },
    { "isInAppNotificationSoundEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeInAppNotificationSoundEnabledWithValue:", "changeInAppNotificationSoundEnabled", "V", 0x1, NULL, NULL },
    { "isInAppNotificationVibrationEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeInAppNotificationVibrationEnabledWithValue:", "changeInAppNotificationVibrationEnabled", "V", 0x1, NULL, NULL },
    { "isGroupNotificationsEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeGroupNotificationsEnabled:", "changeGroupNotificationsEnabled", "V", 0x1, NULL, NULL },
    { "isGroupNotificationsOnlyMentionsEnabled", NULL, "Z", 0x1, NULL, NULL },
    { "changeGroupNotificationsOnlyMentionsEnabled:", "changeGroupNotificationsOnlyMentionsEnabled", "V", 0x1, NULL, NULL },
    { "isRenameHintShown", NULL, "Z", 0x1, NULL, NULL },
    { "getSelectedWallpaper", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "changeSelectedWallpaper:", "changeSelectedWallpaper", "V", 0x1, NULL, NULL },
    { "loadSessionsCommand", "loadSessions", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "terminateAllSessionsCommand", "terminateAllSessions", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "terminateSessionCommandWithId:", "terminateSession", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "startWebAction:", "startWebAction", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "completeWebActionWithHash:withUrl:", "completeWebAction", "Lim.actor.core.viewmodel.Command;", 0x1, NULL, NULL },
    { "getFormatter", NULL, "Lim.actor.core.i18n.I18nEngine;", 0x1, NULL, NULL },
    { "registerGooglePushWithProjectId:withToken:", "registerGooglePush", "V", 0x1, NULL, NULL },
    { "registerApplePushWithApnsId:withToken:", "registerApplePush", "V", 0x1, NULL, NULL },
    { "getPreferences", NULL, "Lim.actor.runtime.storage.PreferencesStorage;", 0x1, NULL, NULL },
    { "forceNetworkCheck", NULL, "V", 0x1, NULL, NULL },
    { "getModuleContext", NULL, "Lim.actor.core.modules.ModuleContext;", 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "modules_", NULL, 0x4, "Lim.actor.core.modules.Modules;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ACMessenger = { 2, "Messenger", "im.actor.core", NULL, 0x1, 137, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ACMessenger;
}

@end


#line 74
void ACMessenger_initWithConfiguration_(ACMessenger *self, ACConfiguration *configuration) {
  (void) NSObject_init(self);
  
#line 79
  ACTiming *timing = new_ACTiming_initWithNSString_(@"MESSENGER_INIT");
  
#line 82
  [timing sectionWithNSString:@"Actors"];
  [((ARActorSystem *) nil_chk(ARActorSystem_system())) setTraceInterfaceWithARTraceInterface:new_ACActorTrace_init()];
  [((ARActorSystem *) nil_chk(ARActorSystem_system())) addDispatcherWithNSString:@"network"];
  [((ARActorSystem *) nil_chk(ARActorSystem_system())) addDispatcherWithNSString:@"heavy"];
  [((ARActorSystem *) nil_chk(ARActorSystem_system())) addDispatcherWithNSString:@"updates" withInt:1];
  
#line 88
  [timing sectionWithNSString:@"Modules:Create"];
  self->modules_ = new_ACModules_initWithACMessenger_withACConfiguration_(self, configuration);
  
#line 91
  [timing end];
}


#line 74
ACMessenger *new_ACMessenger_initWithConfiguration_(ACConfiguration *configuration) {
  ACMessenger *self = [ACMessenger alloc];
  ACMessenger_initWithConfiguration_(self, configuration);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ACMessenger)

#pragma clang diagnostic pop
