//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-cocoa/src/main/java//im/actor/runtime/cocoa/CocoaNetworkProxyProvider.java
//

#include <j2objc/IOSClass.h>
#include <j2objc/J2ObjC_source.h>
#include "com/google/j2objc/annotations/ObjectiveCName.h"
#include "im/actor/runtime/NetworkRuntime.h"
#include "im/actor/runtime/cocoa/CocoaNetworkProxyProvider.h"
#include "im/actor/runtime/mtproto/ConnectionCallback.h"
#include "im/actor/runtime/mtproto/ConnectionEndpoint.h"
#include "im/actor/runtime/mtproto/CreateConnectionCallback.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

static id<ARNetworkRuntime> ARCocoaNetworkProxyProvider_networkRuntime_;
J2OBJC_STATIC_FIELD_GETTER(ARCocoaNetworkProxyProvider, networkRuntime_, id<ARNetworkRuntime>)
J2OBJC_STATIC_FIELD_SETTER(ARCocoaNetworkProxyProvider, networkRuntime_, id<ARNetworkRuntime>)

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-cocoa/src/main/java//im/actor/runtime/cocoa/CocoaNetworkProxyProvider.java"


#line 10
@implementation ARCocoaNetworkProxyProvider


#line 15
+ (void)setNetworkRuntime:(id<ARNetworkRuntime>)networkRuntime {
  ARCocoaNetworkProxyProvider_setNetworkRuntime_(networkRuntime);
}


#line 20
- (void)createConnectionWithId:(jint)connectionId
                 withMTVersion:(jint)mtprotoVersion
                  withApiMajor:(jint)apiMajorVersion
                  withApiMinor:(jint)apiMinorVersion
                  withEndpoint:(ARConnectionEndpoint *)endpoint
                  withCallback:(id<ARConnectionCallback>)callback
            withCreateCallback:(id<ARCreateConnectionCallback>)createCallback {
  
#line 22
  [((id<ARNetworkRuntime>) nil_chk(ARCocoaNetworkProxyProvider_networkRuntime_)) createConnectionWithId:connectionId withMTVersion:mtprotoVersion withApiMajor:apiMajorVersion withApiMinor:apiMinorVersion withEndpoint:endpoint withCallback:callback withCreateCallback:createCallback];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ARCocoaNetworkProxyProvider_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (IOSObjectArray *)__annotations_setNetworkRuntimeWithARNetworkRuntime_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[ComGoogleJ2objcAnnotationsObjectiveCName alloc] initWithValue:@"setNetworkRuntime:"] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setNetworkRuntime:", "setNetworkRuntime", "V", 0x9, NULL, NULL },
    { "createConnectionWithId:withMTVersion:withApiMajor:withApiMinor:withEndpoint:withCallback:withCreateCallback:", "createConnection", "V", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "networkRuntime_", NULL, 0xa, "Lim.actor.runtime.NetworkRuntime;", &ARCocoaNetworkProxyProvider_networkRuntime_, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ARCocoaNetworkProxyProvider = { 2, "CocoaNetworkProxyProvider", "im.actor.runtime.cocoa", NULL, 0x1, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ARCocoaNetworkProxyProvider;
}

@end


#line 15
void ARCocoaNetworkProxyProvider_setNetworkRuntime_(id<ARNetworkRuntime> networkRuntime) {
  ARCocoaNetworkProxyProvider_initialize();
  
#line 16
  ARCocoaNetworkProxyProvider_networkRuntime_ = networkRuntime;
}

void ARCocoaNetworkProxyProvider_init(ARCocoaNetworkProxyProvider *self) {
  (void) NSObject_init(self);
}

ARCocoaNetworkProxyProvider *new_ARCocoaNetworkProxyProvider_init() {
  ARCocoaNetworkProxyProvider *self = [ARCocoaNetworkProxyProvider alloc];
  ARCocoaNetworkProxyProvider_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ARCocoaNetworkProxyProvider)

#pragma clang diagnostic pop
