//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/ApiDocumentExVideo.java
//

#ifndef _ImActorCoreApiApiDocumentExVideo_H_
#define _ImActorCoreApiApiDocumentExVideo_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/core/api/ApiDocumentEx.h>

@class ARBserValues;
@class ARBserWriter;

@interface ARApiDocumentExVideo : ARApiDocumentEx

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)w
                    withInt:(jint)h
                    withInt:(jint)duration;

- (jint)getDuration;

- (jint)getH;

- (jint)getHeader;

- (jint)getW;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiDocumentExVideo)

FOUNDATION_EXPORT void ARApiDocumentExVideo_initWithInt_withInt_withInt_(ARApiDocumentExVideo *self, jint w, jint h, jint duration);

FOUNDATION_EXPORT ARApiDocumentExVideo *new_ARApiDocumentExVideo_initWithInt_withInt_withInt_(jint w, jint h, jint duration) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARApiDocumentExVideo_init(ARApiDocumentExVideo *self);

FOUNDATION_EXPORT ARApiDocumentExVideo *new_ARApiDocumentExVideo_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARApiDocumentExVideo)

@compatibility_alias ImActorCoreApiApiDocumentExVideo ARApiDocumentExVideo;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiApiDocumentExVideo_H_
