//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/ApiDocumentEx.java
//

#ifndef _ImActorCoreApiApiDocumentEx_H_
#define _ImActorCoreApiApiDocumentEx_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/runtime/bser/BserObject.h"

@class IOSByteArray;

@interface ARApiDocumentEx : ARBserObject

#pragma mark Public

- (instancetype)init;

- (IOSByteArray *)buildContainer;

+ (ARApiDocumentEx *)fromBytesWithByteArray:(IOSByteArray *)src;

- (jint)getHeader;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiDocumentEx)

FOUNDATION_EXPORT ARApiDocumentEx *ARApiDocumentEx_fromBytesWithByteArray_(IOSByteArray *src);

FOUNDATION_EXPORT void ARApiDocumentEx_init(ARApiDocumentEx *self);

J2OBJC_TYPE_LITERAL_HEADER(ARApiDocumentEx)

@compatibility_alias ImActorCoreApiApiDocumentEx ARApiDocumentEx;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiApiDocumentEx_H_
