//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/ApiDialogShort.java
//

#ifndef _ImActorCoreApiApiDialogShort_H_
#define _ImActorCoreApiApiDialogShort_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/runtime/bser/BserObject.h>

@class ARApiPeer;
@class ARBserValues;
@class ARBserWriter;

@interface ARApiDialogShort : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithARApiPeer:(ARApiPeer *)peer
                          withInt:(jint)counter
                         withLong:(jlong)date;

- (jint)getCounter;

- (jlong)getDate;

- (ARApiPeer *)getPeer;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiDialogShort)

FOUNDATION_EXPORT void ARApiDialogShort_initWithARApiPeer_withInt_withLong_(ARApiDialogShort *self, ARApiPeer *peer, jint counter, jlong date);

FOUNDATION_EXPORT ARApiDialogShort *new_ARApiDialogShort_initWithARApiPeer_withInt_withLong_(ARApiPeer *peer, jint counter, jlong date) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARApiDialogShort_init(ARApiDialogShort *self);

FOUNDATION_EXPORT ARApiDialogShort *new_ARApiDialogShort_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARApiDialogShort)

@compatibility_alias ImActorCoreApiApiDialogShort ARApiDialogShort;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiApiDialogShort_H_
