//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/ApiEventRecord.java
//

#ifndef _ImActorCoreApiApiEventRecord_H_
#define _ImActorCoreApiApiEventRecord_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/runtime/bser/BserObject.h"

@class ARApiEvent;
@class ARBserValues;
@class ARBserWriter;

@interface ARApiEventRecord : ARBserObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithLong:(jlong)date
              withARApiEvent:(ARApiEvent *)event;

- (jlong)getDate;

- (ARApiEvent *)getEvent;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiEventRecord)

FOUNDATION_EXPORT void ARApiEventRecord_initWithLong_withARApiEvent_(ARApiEventRecord *self, jlong date, ARApiEvent *event);

FOUNDATION_EXPORT ARApiEventRecord *new_ARApiEventRecord_initWithLong_withARApiEvent_(jlong date, ARApiEvent *event) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARApiEventRecord_init(ARApiEventRecord *self);

FOUNDATION_EXPORT ARApiEventRecord *new_ARApiEventRecord_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARApiEventRecord)

@compatibility_alias ImActorCoreApiApiEventRecord ARApiEventRecord;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiApiEventRecord_H_
