//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/ApiMessage.java
//

#ifndef _ImActorCoreApiApiMessage_H_
#define _ImActorCoreApiApiMessage_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/runtime/bser/BserObject.h"

@class IOSByteArray;

@interface ARApiMessage : ARBserObject

#pragma mark Public

- (instancetype)init;

- (IOSByteArray *)buildContainer;

+ (ARApiMessage *)fromBytesWithByteArray:(IOSByteArray *)src;

- (jint)getHeader;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiMessage)

FOUNDATION_EXPORT ARApiMessage *ARApiMessage_fromBytesWithByteArray_(IOSByteArray *src);

FOUNDATION_EXPORT void ARApiMessage_init(ARApiMessage *self);

J2OBJC_TYPE_LITERAL_HEADER(ARApiMessage)

@compatibility_alias ImActorCoreApiApiMessage ARApiMessage;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiApiMessage_H_
