//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/ApiRule.java
//

#include <j2objc/IOSClass.h>
#include <j2objc/J2ObjC_source.h>
#include "im/actor/core/api/ApiAction.h"
#include "im/actor/core/api/ApiRule.h"
#include "im/actor/runtime/bser/BserObject.h"
#include "im/actor/runtime/bser/BserValues.h"
#include "im/actor/runtime/bser/BserWriter.h"
#include <j2objc/java/io/IOException.h>
#include <j2objc/java/util/List.h>

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ARApiRule () {
 @public
  ARApiActionEnum *action_;
  id<JavaUtilList> longValues_;
  id<JavaUtilList> rawValues_;
}

@end

J2OBJC_FIELD_SETTER(ARApiRule, action_, ARApiActionEnum *)
J2OBJC_FIELD_SETTER(ARApiRule, longValues_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ARApiRule, rawValues_, id<JavaUtilList>)

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/ApiRule.java"


#line 17
@implementation ARApiRule


#line 23
- (instancetype)initWithARApiActionEnum:(ARApiActionEnum *)action
                       withJavaUtilList:(id<JavaUtilList>)longValues
                       withJavaUtilList:(id<JavaUtilList>)rawValues {
  ARApiRule_initWithARApiActionEnum_withJavaUtilList_withJavaUtilList_(self, action, longValues, rawValues);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN

#line 29
- (instancetype)init {
  ARApiRule_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END


#line 34
- (ARApiActionEnum *)getAction {
  return self->action_;
}


#line 39
- (id<JavaUtilList>)getLongValues {
  return self->longValues_;
}


#line 44
- (id<JavaUtilList>)getRawValues {
  return self->rawValues_;
}


#line 49
- (void)parseWithARBserValues:(ARBserValues *)values {
  self->action_ = ARApiActionEnum_parseWithInt_([((ARBserValues *) nil_chk(values)) getIntWithInt:1]);
  self->longValues_ = [values getRepeatedLongWithInt:2];
  self->rawValues_ = [values getRepeatedBytesWithInt:3];
}


#line 56
- (void)serializeWithARBserWriter:(ARBserWriter *)writer {
  if (self->action_ == nil) {
    @throw new_JavaIoIOException_init();
  }
  [((ARBserWriter *) nil_chk(writer)) writeIntWithInt:1 withInt:[((ARApiActionEnum *) nil_chk(self->action_)) getValue]];
  [writer writeRepeatedLongWithInt:2 withJavaUtilList:self->longValues_];
  [writer writeRepeatedBytesWithInt:3 withJavaUtilList:self->rawValues_];
}


#line 66
- (NSString *)description {
  NSString *res = @"struct Rule{";
  (void) JreStrAppendStrong(&res, "$@", @"action=", self->action_);
  (void) JreStrAppendStrong(&res, "$I", @", longValues=", [((id<JavaUtilList>) nil_chk(self->longValues_)) size]);
  (void) JreStrAppendStrong(&res, "$I", @", rawValues=", [((id<JavaUtilList>) nil_chk(self->rawValues_)) size]);
  (void) JreStrAppendStrong(&res, "$", @"}");
  return res;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithARApiActionEnum:withJavaUtilList:withJavaUtilList:", "ApiRule", NULL, 0x1, NULL, NULL },
    { "init", "ApiRule", NULL, 0x1, NULL, NULL },
    { "getAction", NULL, "Lim.actor.core.api.ApiAction;", 0x1, NULL, NULL },
    { "getLongValues", NULL, "Ljava.util.List;", 0x1, NULL, NULL },
    { "getRawValues", NULL, "Ljava.util.List;", 0x1, NULL, NULL },
    { "parseWithARBserValues:", "parse", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "serializeWithARBserWriter:", "serialize", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "action_", NULL, 0x2, "Lim.actor.core.api.ApiAction;", NULL, NULL, .constantValue.asLong = 0 },
    { "longValues_", NULL, 0x2, "Ljava.util.List;", NULL, "Ljava/util/List<Ljava/lang/Long;>;", .constantValue.asLong = 0 },
    { "rawValues_", NULL, 0x2, "Ljava.util.List;", NULL, "Ljava/util/List<L[B;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ARApiRule = { 2, "ApiRule", "im.actor.core.api", NULL, 0x1, 8, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ARApiRule;
}

@end


#line 23
void ARApiRule_initWithARApiActionEnum_withJavaUtilList_withJavaUtilList_(ARApiRule *self, ARApiActionEnum *action, id<JavaUtilList> longValues, id<JavaUtilList> rawValues) {
  (void) ARBserObject_init(self);
  
#line 24
  self->action_ = action;
  self->longValues_ = longValues;
  self->rawValues_ = rawValues;
}


#line 23
ARApiRule *new_ARApiRule_initWithARApiActionEnum_withJavaUtilList_withJavaUtilList_(ARApiActionEnum *action, id<JavaUtilList> longValues, id<JavaUtilList> rawValues) {
  ARApiRule *self = [ARApiRule alloc];
  ARApiRule_initWithARApiActionEnum_withJavaUtilList_withJavaUtilList_(self, action, longValues, rawValues);
  return self;
}

void ARApiRule_init(ARApiRule *self) {
  (void) ARBserObject_init(self);
}


#line 29
ARApiRule *new_ARApiRule_init() {
  ARApiRule *self = [ARApiRule alloc];
  ARApiRule_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ARApiRule)

#pragma clang diagnostic pop
