//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/api/ApiStringValue.java
//

#ifndef _ImActorCoreApiApiStringValue_H_
#define _ImActorCoreApiApiStringValue_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/core/api/ApiRawValue.h"

@class ARBserValues;
@class ARBserWriter;

@interface ARApiStringValue : ARApiRawValue

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)text;

- (jint)getHeader;

- (NSString *)getText;

- (void)parseWithARBserValues:(ARBserValues *)values;

- (void)serializeWithARBserWriter:(ARBserWriter *)writer;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ARApiStringValue)

FOUNDATION_EXPORT void ARApiStringValue_initWithNSString_(ARApiStringValue *self, NSString *text);

FOUNDATION_EXPORT ARApiStringValue *new_ARApiStringValue_initWithNSString_(NSString *text) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ARApiStringValue_init(ARApiStringValue *self);

FOUNDATION_EXPORT ARApiStringValue *new_ARApiStringValue_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ARApiStringValue)

@compatibility_alias ImActorCoreApiApiStringValue ARApiStringValue;


#pragma clang diagnostic pop
#endif // _ImActorCoreApiApiStringValue_H_
