//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/updates/PresenceProcessor.java
//

#ifndef _ImActorCoreModulesUpdatesPresenceProcessor_H_
#define _ImActorCoreModulesUpdatesPresenceProcessor_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include <ActorSDK/im/actor/core/modules/AbsModule.h>

@protocol ACModuleContext;

@interface ACPresenceProcessor : ACAbsModule

#pragma mark Public

- (instancetype)initWithACModuleContext:(id<ACModuleContext>)modules;

- (void)onGroupOnlineWithInt:(jint)gid
                     withInt:(jint)count
                    withLong:(jlong)updateDate;

- (void)onUserLastSeenWithInt:(jint)uid
                      withInt:(jint)date
                     withLong:(jlong)updateDate;

- (void)onUserOfflineWithInt:(jint)uid
                    withLong:(jlong)updateDate;

- (void)onUserOnlineWithInt:(jint)uid
                   withLong:(jlong)updateDate;

@end

J2OBJC_EMPTY_STATIC_INIT(ACPresenceProcessor)

FOUNDATION_EXPORT void ACPresenceProcessor_initWithACModuleContext_(ACPresenceProcessor *self, id<ACModuleContext> modules);

FOUNDATION_EXPORT ACPresenceProcessor *new_ACPresenceProcessor_initWithACModuleContext_(id<ACModuleContext> modules) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACPresenceProcessor)

@compatibility_alias ImActorCoreModulesUpdatesPresenceProcessor ACPresenceProcessor;


#pragma clang diagnostic pop
#endif // _ImActorCoreModulesUpdatesPresenceProcessor_H_
