//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//im/actor/runtime/util/ClassCreator.java
//

#include <j2objc/J2ObjC_source.h>
#include "im/actor/runtime/util/ClassCreator.h"

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

@interface ImActorRuntimeUtilClassCreator : NSObject

@end

#line 0 "/Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/runtime/runtime-shared/src/main/java//im/actor/runtime/util/ClassCreator.java"


#line 8
@implementation ImActorRuntimeUtilClassCreator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "newInstance", NULL, "TT;", 0x401, NULL, "()TT;" },
  };
  static const J2ObjcClassInfo _ImActorRuntimeUtilClassCreator = { 2, "ClassCreator", "im.actor.runtime.util", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_ImActorRuntimeUtilClassCreator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ImActorRuntimeUtilClassCreator)

#pragma clang diagnostic pop
