//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/modules/Errors.java
//

#ifndef _ImActorCoreModulesErrors_H_
#define _ImActorCoreModulesErrors_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>

@interface ACErrors : NSObject

+ (NSString *)LOCAL_EMPTY_PHONE;

+ (NSString *)PHONE_NUMBER_INVALID;

+ (NSString *)LOCAL_INCORRECT_PHONE;

+ (NSString *)PHONE_CODE_EMPTY;

+ (NSString *)LOCAL_CODE_EMPTY;

+ (NSString *)PHONE_CODE_INVALID;

+ (NSString *)PHONE_CODE_EXPIRED;

#pragma mark Public

- (instancetype)init;

+ (NSString *)mapErrorWithNSString:(NSString *)tag;

+ (NSString *)mapErrorWithNSString:(NSString *)tag
                      withNSString:(NSString *)defVal;

@end

J2OBJC_STATIC_INIT(ACErrors)

FOUNDATION_EXPORT NSString *ACErrors_LOCAL_EMPTY_PHONE_;
J2OBJC_STATIC_FIELD_GETTER(ACErrors, LOCAL_EMPTY_PHONE_, NSString *)

FOUNDATION_EXPORT NSString *ACErrors_PHONE_NUMBER_INVALID_;
J2OBJC_STATIC_FIELD_GETTER(ACErrors, PHONE_NUMBER_INVALID_, NSString *)

FOUNDATION_EXPORT NSString *ACErrors_LOCAL_INCORRECT_PHONE_;
J2OBJC_STATIC_FIELD_GETTER(ACErrors, LOCAL_INCORRECT_PHONE_, NSString *)

FOUNDATION_EXPORT NSString *ACErrors_PHONE_CODE_EMPTY_;
J2OBJC_STATIC_FIELD_GETTER(ACErrors, PHONE_CODE_EMPTY_, NSString *)

FOUNDATION_EXPORT NSString *ACErrors_LOCAL_CODE_EMPTY_;
J2OBJC_STATIC_FIELD_GETTER(ACErrors, LOCAL_CODE_EMPTY_, NSString *)

FOUNDATION_EXPORT NSString *ACErrors_PHONE_CODE_INVALID_;
J2OBJC_STATIC_FIELD_GETTER(ACErrors, PHONE_CODE_INVALID_, NSString *)

FOUNDATION_EXPORT NSString *ACErrors_PHONE_CODE_EXPIRED_;
J2OBJC_STATIC_FIELD_GETTER(ACErrors, PHONE_CODE_EXPIRED_, NSString *)

FOUNDATION_EXPORT NSString *ACErrors_mapErrorWithNSString_(NSString *tag);

FOUNDATION_EXPORT NSString *ACErrors_mapErrorWithNSString_withNSString_(NSString *tag, NSString *defVal);

FOUNDATION_EXPORT void ACErrors_init(ACErrors *self);

FOUNDATION_EXPORT ACErrors *new_ACErrors_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACErrors)

@compatibility_alias ImActorCoreModulesErrors ACErrors;


#pragma clang diagnostic pop
#endif // _ImActorCoreModulesErrors_H_
