//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/ex3ndr/Develop/actor-proprietary/actor-sdk/sdk-core/core/core-shared/src/main/java//im/actor/core/network/mtp/entity/ProtoPackage.java
//

#ifndef _ImActorCoreNetworkMtpEntityProtoPackage_H_
#define _ImActorCoreNetworkMtpEntityProtoPackage_H_

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include <j2objc/J2ObjC_header.h>
#include "im/actor/core/network/mtp/entity/ProtoObject.h"

@class ACProtoMessage;
@class ARDataInput;
@class ARDataOutput;

@interface ACProtoPackage : ACProtoObject

#pragma mark Public

- (instancetype)initWithARDataInput:(ARDataInput *)stream;

- (instancetype)initWithLong:(jlong)authId
                    withLong:(jlong)sessionId
          withACProtoMessage:(ACProtoMessage *)payload;

- (jlong)getAuthId;

- (ACProtoMessage *)getPayload;

- (jlong)getSessionId;

- (ACProtoObject *)readObjectWithARDataInput:(ARDataInput *)bs;

- (NSString *)description;

- (void)writeObjectWithARDataOutput:(ARDataOutput *)bs;

@end

J2OBJC_EMPTY_STATIC_INIT(ACProtoPackage)

FOUNDATION_EXPORT void ACProtoPackage_initWithARDataInput_(ACProtoPackage *self, ARDataInput *stream);

FOUNDATION_EXPORT ACProtoPackage *new_ACProtoPackage_initWithARDataInput_(ARDataInput *stream) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ACProtoPackage_initWithLong_withLong_withACProtoMessage_(ACProtoPackage *self, jlong authId, jlong sessionId, ACProtoMessage *payload);

FOUNDATION_EXPORT ACProtoPackage *new_ACProtoPackage_initWithLong_withLong_withACProtoMessage_(jlong authId, jlong sessionId, ACProtoMessage *payload) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ACProtoPackage)

@compatibility_alias ImActorCoreNetworkMtpEntityProtoPackage ACProtoPackage;


#pragma clang diagnostic pop
#endif // _ImActorCoreNetworkMtpEntityProtoPackage_H_
